<?php 
header('P3P: CP="IDC DSP COR CURa ADMa OUR IND PHY ONL COM STA"');
?>
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
<?php 
	$translate = Zend_Registry::get('TranslationObject');
	$config = Zend_Registry::get('appConfig');
        $locale = $translate->getLocale();
	echo $this->headMeta();
	if(strlen($this->headTitle())>1) echo $this->headTitle(); else echo "<title>".$config->ymoney->APP_NAME."</title>";
?>

<link rel="stylesheet" href="<?php echo $this->baseUrl('css/ym_fb.css')?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/jquery-ui-1.8.16.custom.css')?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/jquery.fancybox-1.3.4.css')?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/reset.css')?>" type="text/css" media="screen" />
<script type='text/javascript' src='<?php echo $this->baseUrl('js/jquery-1.7.1.min.js')?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/jquery.validate.min.js')?>'></script>
<script src="https://connect.facebook.net/en_US/all.js?xfbml=1&appId=<?php echo $config->ymoney->APP_ID?>" type="text/javascript"></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/jquery-ui-1.8.16.custom.min.js')?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/jquery.ui.datepicker-ru.js')?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/popup.js')?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/jquery.fancybox-1.3.4.js')?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/scripts.js')?>'></script>

<?php echo $this->headScript(); ?>
</head>
<body>
<div id="fb-root"></div>
<script>
  FB.init({
    appId      : '<?php echo $config->ymoney->APP_ID?>',
    status     : true, // check login status
    cookie     : true, // enable cookies to allow the server to access the session
    oauth      : true, // enable OAuth 2.0
    xfbml      : true  // parse XFBML
  });
window.fbAsyncInit = function() {
	FB.Canvas.setAutoGrow();
};
</script>

<div class="wrapper">
	<?php echo $this->layout()->content; ?>
</div>
</body>
</html>