<?php
header('P3P: CP="IDC DSP COR CURa ADMa OUR IND PHY ONL COM STA"');
?>
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
	$translate = Zend_Registry::get('TranslationObject');
	$config = Zend_Registry::get('appConfig');
    $locale = $translate->getLocale();
	echo $this->headMeta();
	if(strlen($this->headTitle())>1) echo $this->headTitle(); else echo "<title>".$config->ymoney->APP_NAME."</title>";
?>

<link rel="stylesheet" href="<?php echo $this->baseUrl('css/ym_fb.css')?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/jquery-ui-1.8.16.custom.css')?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/jquery.fancybox-1.3.4.css')?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/reset.css')?>" type="text/css" media="screen" />
<script type='text/javascript' src='<?php echo $this->baseUrl('js/jquery-1.7.1.min.js')?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/jquery.validate.min.js')?>'></script>
<script src="https://vkontakte.ru/js/api/xd_connection.js" type="text/javascript"></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/jquery-ui-1.8.16.custom.min.js')?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/jquery.ui.datepicker-ru.js')?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/popup.js')?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/jquery.fancybox-1.3.4.js')?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/scripts.js')?>'></script>

<script type="text/javascript">
  VK.init();
</script>
<?php echo $this->headScript(); ?>
</head>
<body>


<div class="wrapper">
	<?php echo $this->layout()->content; ?>
</div>
</body>
</html>