<script type='text/javascript' src='<?php echo $this->baseUrl('js/create_edit.js')?>'></script>
<link href="<?php echo $this->baseUrl('css/fileuploader.css')?>" rel="stylesheet" type="text/css">
<script src="<?php echo $this->baseUrl('js/fileuploader.js')?>" type="text/javascript"></script>
<script>
/* ABOUT MONEY */
var bal = <?php echo $this->balance ?>;
var action_id = '<?php echo $this->action['id'] ?>';
var curbal = 0;
//var previousUrl = '<?php echo $this->hostUrl . "/actions/index"; ?>';
var adminEdit = 0;


$(function() {
    /* select variant */
    $('#cash_variants li').each(function(CVI) {

    	if($(this).hasClass('curr') && CVI==0) {   		
        	if($('#required_sum').val().replace(' ', '').replace(',', '.')>0) {
    			setrightwreq(); //$('.right .mb_collected').html('Collected <span class="s1">'+(Number($('#current_sum').val().replace(' ', '').replace(',', '.'))+bal)+'</span> из <span class="s2">' + Number($('#required_sum').val().replace(' ', '').replace(',', '.')) + '</span> <span>rub.</span>');
    		} else {
    			setrightworeq(); //$('.right .mb_collected').html('Collected <span class="s1">'+(Number($('#current_sum').val().replace(' ', '').replace(',', '.'))+bal)+'</span> <span>rub.</span>');
    		}
    	}
    	
        $(this).click(function() {
            $('#cash_variants li').removeClass('curr');
            $(this).addClass('curr');
            $('#cash_variants input').attr('value',CVI);
            /* show/hide hidden rows */
            if(CVI==0||CVI==2) { $('.mbegin').addClass('tr_closed'); }
            if(CVI==1) { $('.mbegin').removeClass('tr_closed'); }
            $('.cv_info').removeClass('cv_show'); $('.cv_info').eq(CVI).addClass('cv_show');
            if(CVI==0) {
            	sumbalance();
                if(!isNaN(toHumanNumber($('#required_sum').val())) && !isNaN(toHumanNumber($('#current_sum').val()))) {
	            	if(toHumanNumber($('#required_sum').val())>0) {
	            		setrightwreq();
	        		} else {
	        			setrightworeq();
	        		}
            	} else if (isNaN(toHumanNumber($('#required_sum').val())) && !isNaN(toHumanNumber($('#current_sum').val()))) {
            		setrightworeq();
            	} else if (isNaN(toHumanNumber($('#required_sum').val())) && isNaN(toHumanNumber($('#current_sum').val()))) {
            		setrightWoReqWBal();
            	} else if (!isNaN(toHumanNumber($('#required_sum').val())) && isNaN(toHumanNumber($('#current_sum').val()))) {
            		setrightWithReqWoBal();
            	}
            } else if(CVI==2) {
            	$('.about_money td.inp p').first().html('rub.');
            } else {
            	sumbalance();
            }
        });
    });
});

//function sumbalance()
//{
//	var newbal = bal;
//	if(!isNaN(toHumanNumber($('#current_sum').val())) && $('#cash_variants input').attr('value')==0) {
//		newbal = toHumanNumber($('#current_sum').val())+bal;
//	} else if(!isNaN(toHumanNumber($('#current_sum').val())) && $('#cash_variants input').attr('value')!=0) {
//		newbal = toHumanNumber($('#current_sum').val());
//	}
//	if($('#cash_variants input').attr('value')!=0) {
//		$('.about_money td.inp p').first().html('rub.');
//	} else {
//		$('.about_money td.inp p').first().html('rub. (всего &ndash; <span>' + formatMoney(newbal) + ' rub.</span>)');
//	}
//}

//function checkname()
//{
//	var name = $('#name').val();
//
//	$.ajax({
//        url: checknameAjaxUrl,
//        type: "GET",
//        dataType: "json",
//		data: {
//			name: name
//		},
//        success: function (data) { 
//        	if(data == true) {
//        		$('#name').css("border", '1px solid #F00');
//            	goodname = false;
//        	} else {
//        		$('#name').css("border", '1px solid #BDC6D9');
//        		goodname = true;
//        	}
//        }
//	});
//}

//function updateRightBalance()
//{
//	if($('input[name="source"]').val()!='2' && $('input[name="source"]').val()!='1') {
//		curbal = bal;
//	}
//	if(!isNaN(toHumanNumber($('#required_sum').val())) && !isNaN(toHumanNumber($('#current_sum').val()))) {
//		if($('#required_sum').val()>0) {
//    		setrightwreqC();
//		} else {
//			setrightworeqC();
//		}
//	} else if(isNaN(toHumanNumber($('#required_sum').val())) && !isNaN(toHumanNumber($('#current_sum').val()))) {
//		setrightworeqC();
//	} else if(!isNaN(toHumanNumber($('#required_sum').val())) && isNaN(toHumanNumber($('#current_sum').val()))) {
//		setrightWithReqWoBal();
//	} else {
//		setrightWoReqWBalC();
//	}
//}

//function createUploader() {
//    var uploader = new qq.FileUploader({
//        element: $('#popup_tpl #file-uploader-demo1')[0],
//        action: '/actions/loadimageajax',
//        debug: false,
//        allowedExtensions: ['jpg', 'jpeg', 'png', 'gif'],
//        onComplete: function(id, fileName, responseJSON) {
//            data = JSON.parse(responseJSON.data);
//            $('.p_pad #photos').prepend('<a class="selectphoto" pid="photo'+data[0].pid+'" href="#"><img src="'+data[0].src+'" /></a>');
//            $('.listphoto #photos').prepend('<a class="selectphoto" pid="photo'+data[0].pid+'" href="#"><img src="'+data[0].src+'" /></a>');
//            $('.p_pad a[pid="photo'+data[0].pid+'"]').click();
//            $('.qq-upload-list').empty();
//            FB.Canvas.setAutoGrow();
//        }
//    });
//}

$(document).ready(function(){
	$('#draftbutton').click(function(){
		var name = $('#name').val();
		if(name.replace(/\s+/g, '').length==0 || $.trim(name.replace(/(<([^>]+)>)/ig,"")).length==0) {
			$('#name').css("border", '1px solid #F00');
        	goodname = false;
        	return false;
		}
                if(parseInt($('#required_sum').val()) > 1000000000 || parseInt($('#required_sum').val()) < 1) {
                    $('#required_sum').css("border", '1px solid red');
                    return false;
                }
                if(parseInt($('#current_sum').val()) >= parseInt($('#required_sum').val()) ||
                    //не ржать - требования тестера
                    ($('#current_sum').val() == '' && parseInt($('#required_sum').val() == 0))) {
                    $('#current_sum').css("border", '1px solid red');
                    return false;
                }
                if($('#groupselect').val() == 1) {
                    if($(".insertedfriends").length == 0) {
                        $(".friends").css("color", "red");
                        return false;
                    };
                }
		$.ajax({
	        url: checknameAjaxUrl,
	        type: "GET",
	        dataType: "json",
			data: {
				name: name
			},
	        success: function (data) { 
	        	if(data == true) {
	        		$('#name').css("border", '1px solid #F00');
	            	goodname = false;
	            	$('#name').focus();
	        	} else {
	        		$('#name').css("border", '1px solid #BDC6D9');
	        		goodname = true;
	        		$('#draft').val('Y');
	    			$('#actionform').submit();
	        	}
	        }
		});
		return false;
	});
	
        $('#publicbutton').click(function(){
		var name = $('#name').val();
		if(name.replace(/\s+/g, '').length==0 || $.trim(name.replace(/(<([^>]+)>)/ig,"")).length==0) {
			$('#name').css("border", '1px solid #F00');
        	goodname = false;
        	return false;
		}
                if(parseInt($('#required_sum').val()) > 1000000000 || parseInt($('#required_sum').val()) < 1) {
                    $('#required_sum').css("border", '1px solid red');
                    return false;
                }
                if(parseInt($('#current_sum').val()) >= parseInt($('#required_sum').val()) ||
                    //не ржать - требования тестера
                    ($('#current_sum').val() == '' && parseInt($('#required_sum').val() == 0))) {
                    $('#current_sum').css("border", '1px solid red');
                    return false;
                }
                if($('#groupselect').val() == 1) {
                    if($(".insertedfriends").length == 0) {
                        $(".friends").css("color", "red");
                        return false;
                    };
                }
		$.ajax({
	        url: checknameAjaxUrl,
	        type: "GET",
	        dataType: "json",
			data: {
				name: name
			},
	        success: function (data) { 
	        	if(data == true) {
	        		$('#name').css("border", '1px solid #F00');
	            	goodname = false;
	            	$('#name').focus();
	        	} else {
	        		$('#name').css("border", '1px solid #BDC6D9');
	        		goodname = true;
	        		$('#draft').val('N');
	    			$('#actionform').submit();
	        	}
	        }
		});
		return false;
	});
	
	$('.right').hide();
	var hidden = true;
	var goodname = true;
	var friendsIsLoaded = false;
	$('#name').blur(function(){
		var name = $(this).val();
		checkname();
		if(name.length<=50) {
			$('.right .mb_title a').first().html(name);
		} else {
			$('.right .mb_title a').first().html(name.slice(0, 50) + '…');
		}
                if($('.right .mb_title a').width() > $('.right .mb_title').width()) {
                    tmparr = name.split(' ');
                    ind = 0;
                    for(i = 1; i < tmparr.length; i++) {
                        if(tmparr[i].length > tmparr[i-1].length) {
                            ind = i;                                
                        }
                    }
                    keyLength = $('.right .mb_title a').width() / tmparr[ind].length;
                    for(i = 0; i < tmparr.length; i++) {
                        if(tmparr[i].length * keyLength > $('.right .mb_title').width()) {
                            keyNums = Math.round((tmparr[i].length * keyLength - $('.right .mb_title').width()) / keyLength);
                            tmparr.length = i+1;
                            tmpstr = tmparr.join(' ');
                            $('.right .mb_title a').first().html(tmpstr.substring(0, tmpstr.length - keyNums - 4) + '…');
                            break;
                        }                                                        
                    }
                }

		settime();
		if (hideRight()) hidden = true;
		updateRightBalance();
	});

	$('#name').keyup(function(){
		if(hidden) {
			showRight();	
			hidden = false;		
		}
		var name = $(this).val();
		checkname();

                $('.right .mb_title a').first().html(name);
                
                if($('.right .mb_title a').width() > $('.right .mb_title').width()) {
                    tmparr = name.split(' ');
                    ind = 0;
                    for(i = 1; i < tmparr.length; i++) {
                        if(tmparr[i].length > tmparr[i-1].length) {
                            ind = i;                                
                        }
                    }
                    keyLength = $('.right .mb_title a').width() / tmparr[ind].length;
                    for(i = 0; i < tmparr.length; i++) {
                        if(tmparr[i].length * keyLength > $('.right .mb_title').width()) {
                            keyNums = Math.round((tmparr[i].length * keyLength - $('.right .mb_title').width()) / keyLength);
                            tmparr.length = i+1;
                            tmpstr = tmparr.join(' ');
                            $('.right .mb_title a').first().html(tmpstr.substring(0, tmpstr.length - keyNums - 4) + '…');
                            break;
                        }                                                        
                    }
                } else { 
                    if(name.length<=50) {
                            $('.right .mb_title a').first().html(name);
                    } else {
                            $('.right .mb_title a').first().html(name.slice(0, 50) + '…');
                    }
                }
		
		settime();
		if (hideRight()) hidden = true;
                updateRightBalance();
	});
        
        $('#date1 .datepicker, #date2 .datepicker').change(function() {
            settime();
        });
        
        $('#date2 .datepicker').click(function() {
            if($('#signal:checked').length) {
                    $('#signal').prop('checked', false);
            }
        });
        
        var tmp = new Date();
        var date1 = $('#date1 .datepicker').datepicker("getDate");
        $('#date1 .datepicker').datepicker("option", "minDate", tmp);
        
        date1.setDate(date1.getDate() + 1);
        tmp = $.datepicker.formatDate('yy-mm-dd', new Date());
        $('#date2 .datepicker').datepicker("option", "minDate", date1 < tmp ? date1 : tmp);
        
        $('#signal').change(function() {
            if($('#date2 .datepicker').val().length != 0) {
                settime();
            }
        });
	
        $('#current_sum').keyup(function(){
		if(hidden) {
			showRight();	
			hidden = false;		
		}
		updateRightBalance();
		sumbalance();
		settime();
		if (hideRight()) hidden = true;
	});
	
        $('#required_sum').keyup(function(){
		if(hidden) {
			showRight();	
			hidden = false;		
		}

		if($('.insertedfriends').size()>0) {
			$('#required_sum_group').val(Math.round(100*$(this).val()/($('.insertedfriends').size()+1))/100);
		}
		
		updateRightBalance();
		sumbalance();
		settime();
		if (hideRight()) hidden = true;
	});
        
	$('#required_sum_group').keyup(function(){
		if(hidden) {
			showRight();	
			hidden = false;		
		}
		
		if($('.insertedfriends').size()>0) {
			$('#required_sum').val(Math.round(100*$(this).val()*($('.insertedfriends').size()+1))/100);
		}
		
		updateRightBalance();
		sumbalance();
		settime();
		if (hideRight()) hidden = true;
	});
	

	$('#required_sum').click(function(){
		if($('#required_sum').val()==0) {
			$('#required_sum').val('');	
		}
	});
	$('#current_sum').blur(function(){
		if($('#current_sum').val()=='') {
			$('#current_sum').val('0');	
		}
	});
	$('#current_sum').click(function(){
		if($('#current_sum').val()==0) {
			$('#current_sum').val('');	
		}
	});

	jQuery.validator.addMethod("number", function(value, element) { 
		//alert(/^\d*[\.|\,]*\d+$/.test(value));
		if(/^\d*[\.|\,|\s]*\d+$/.test(value) || value=='') {
			$(element).css("border", '1px solid #BDC6D9');
			return true;
		} else {
			return false;
		}
	}, '');
	
//	var formValidator = $('#actionform').validate({
//            errorPlacement: function(error, element) {
//                    element.css("border", 'red 1px solid');
//            },
//            rules: {
//                'video': {
//                    url: true
//                },
//                'current_sum': {
//                    number: true
//                },
//                'required_sum': {
//                    number: true
//                },
//                'required_sum_group': {
//                    number: true
//                }
//            }
//        });

//	/* add photo */
//        $('.selectphoto').live('click', function(){
//            if($(this).attr('class') == 'selectphoto selected') {
//                    $(this).removeClass('selected');
//                    //alert($('.photocontainer').find('input[value="'+$(this).attr('pid').replace('photo', '')+'"]').length);
//                    //$('.photocontainer').find('input[value="'+$(this).attr('pid').replace('photo', '')+'"]').remove();
//                    $('.listphoto a[pid="'+$(this).attr('pid')+'"]').removeClass('selected');
//                    $('.photocontainer').find('#'+$(this).attr('pid').replace('photo', 'img')).remove();
//            } else {
//                    $(this).addClass('selected');
//                    $('.listphoto a[pid="'+$(this).attr('pid')+'"]').addClass('selected');
//                    $('.photocontainer').append('<table id="'+$(this).attr('pid').replace('photo', 'img')+'"><tr><td><a href="#" class="del_photo"></a><input type="hidden" name="photo['+fileCounter+']" value="'+$(this).attr('pid').replace('photo', '')+'" /><img src="'+$(this).find('img').attr('src')+'" valign="middle"/></td></tr></table>');
//                fileCounter++;
//            }
//            FB.Canvas.setAutoGrow();
//        });
	
//	$('.del_photo').live('click', function() {
//		var table_id = $(this).siblings('input').val();
//		$('.listphoto a[pid=photo'+table_id+']').removeClass('selected');
//                $('table#img'+table_id).remove();
//                FB.Canvas.setAutoGrow();
//                return false;
//        });
	
//	var offset = 0;
//        var first = true;
//	$('.add_photo a').click(function() {
//		$(this).fb_popup({
//			content_container: '.listphoto',
//			//content:'',
//			title: 'Выберите фото',
//			popup_id: 'popup_tpl',
//			width: 760,
//			height: 450,
//			overflow: 'auto'
//		});
//                createUploader();
//                if(first == true) {
//                    loadPhotos(offset);
//                }
//                first = false;
//                
//                return false;
//        });
//        
//        function loadPhotos(offset) {
//            $.ajax({
//                url: getphotoAjaxUrl,
//                type: "POST",
//                dataType: "json",
//                data: {
//                    offset: offset
//                },
//                success: function (data) { 
//                    if(data.length > 0) {
//                        $('.morephoto').remove();
//                        jQuery.each(data, function(i, element){
//                            $('.p_pad #photos').append('<a class="selectphoto" pid="photo'+element['pid']+'" href="#"><img src="'+element['src']+'" /></a>');
//                            $('.listphoto #photos').append('<a class="selectphoto" pid="photo'+element['pid']+'" href="#"><img src="'+element['src']+'" /></a>');
//                        });
//                        $('.p_pad').append('<div class="morephoto"><a href="#">Еще...</a></div>');
//                        $('.listphoto').append('<div class="morephoto"><a href="#">Еще...</a></div>');
//                        if(data.length<50) {
//                            $('.morephoto').remove();
//                        }
//                        FB.Canvas.setAutoGrow();
//                    } else {
//                        $('.morephoto').remove();
//                    }
//                }                
//            });            
//        }
//        
//        $('.morephoto').live("click", function(){
//            loadPhotos(offset);
//            offset += 50;
//            
//            return false;
//        });

//        $('.tabs ul li a.simple-action').live("click", function(){
//            $('.tabs ul li.simple-action').addClass('current_link');
//            $('.tabs ul li.for-friends').removeClass('current_link');
//            $('.tabs ul li.for-friends').html('<a href="#" class="for-friends"><span class="tl"><span class="tr">Новая акция для друзей</span></span></a>');
//            $('#group').val(0);
//            $('.about_friends, .grouptr').slideUp('slow');
//                    $(this).replaceWith('<span>' + $(this).html() + '</span>');
//                    FB.Canvas.setAutoGrow();
//                    return false;
//        });
//
//        $('.tabs ul li a.for-friends').live("click", function(){
//            $('.tabs ul li.for-friends').addClass('current_link');
//            $('.tabs ul li.simple-action').removeClass('current_link');
//            $('.tabs ul li.simple-action').html('<a href="#" class="simple-action"><span class="tl"><span class="tr">Новая акция</span></span></a>');
//            $('#group').val(1);
//            $('.about_friends, .grouptr').slideDown('slow');
//                    $(this).replaceWith('<span>' + $(this).html() + '</span>');
//                    FB.Canvas.setAutoGrow();
//                    return false;
//        });

        $('.friends a').live('click', function(){
            $(this).parent().css("color", "#666666");
            $(this).fb_popup({
                            content_container: '.friendlist',
                            //content:'',
                            title: 'Select friends',
                            popup_id: 'popup_tpl',
                            width: 530,
                            height: 450,
                            overflow: 'auto'
                    });
            if(!friendsIsLoaded) {
                    FB.api('/me/friends', function(response) {
                            var links = '';
                            var data = response["data"];
                            if(data.length > 0) {
                            jQuery.each(data, function(i, element){
                                    links = '<table><tr><td>'+element['name']+'</td><td class="friendcheckbox">' + '<input type="checkbox" id="friend'+element['id']+'" value="'+element['id']+'"/></td></tr></table>';
                                            $('.p_pad').append(links);
                                            $('.friendlist').append(links);
                            });
                            friendsIsLoaded = true;
                                    FB.Canvas.setAutoGrow();
                            }
                            });
            }
            return false;
        });
        
        var checkedfriends;
        $('.friendcheckbox input').live('click', function(){
            if($(this).is(':checked')) {
                    checkedfriends = '<input type="hidden" value="'+$(this).val()+'" name="friends[]" id="checkedfriend'+$(this).val()+'" class="insertedfriends"/>';
                    $(checkedfriends).appendTo('#actionform');
                    $('#friend'+$(this).val()).attr('checked', 'checked');
            } else {
                $("#checkedfriend"+$(this).val()).remove();
                $('#friend'+$(this).val()).attr('checked', false);
            }
            $('.friends span').html($('.insertedfriends').size());
            if($('.insertedfriends').size()>0 && $('#required_sum').val()>0) {
                $('#required_sum_group').val(Math.round(100*$('#required_sum').val()/($('.insertedfriends').size()+1))/100);
            }
            if($('.insertedfriends').size()==0) {
                $('#required_sum_group').val($('#required_sum').val());
            }
        });  
});
//$(document).ajaxStart(function(){ 
//	$('.morephoto').append('<span class="loading"></span>'); 
//}).ajaxStop(function(){ 
//	$('.morephoto span').remove();
//});
</script>

<div class="header">

	<a href="<?php echo $this->appurl?>" target="_top" class="logo"></a>

	<div class="header_links">

		<a href="<?php echo $this->appurl?>?app_data=21354-52934" target="_top">All collections</a> &#0149; 
		<a href="<?php echo $this->appurl?>?app_data=21354-48523" target="_top">My collections</a> &#0149; 
		<a href="<?php echo $this->appurl?>?app_data=21354-98347" target="_top">Account information</a>
                <?php if ($this->admin) { ?> &#0149; <a href="/actions/adminstat">Statistics</a> &#0149; <a href="/actions/duplicates">Duplicates</a>
                    &#0149; <a href="/actions/admins">Admins</a><?php } ?>

	</div>

</div>
<!--<div class="tabs">
	<ul>
		<li class="current_link simple-action">
			<span><span class="tl"><span class="tr">Новая акция</span></span></span>
		</li>
		<li class="for-friends">
			<a href="#" class="for-friends"><span class="tl"><span class="tr">Новая акция для друзей</span></span></a>
		</li>
	</ul>
</div>-->
<div class="content">
<div class="admin">
        <div class="title3">New collection description</div>
        <div class="left">
                <form action="" method="post" enctype="multipart/form-data" id="actionform">
                        <div class="new_action">
                                <table>
                                        <tr><td>Reason for collection:</td><td class="inp"><input name="name" maxlength="60" type="text" id="name"/></td></tr>
                                        <tr><td>More details:</td><td class="inp"><textarea name="description" cols="" rows=""></textarea></td></tr>
                                        <tr><td>Remarks:</td><td class="inp"><input name="tags" type="text" /></td></tr>
                                        <tr class="period"><td>Time period:</td><td class="inp">
                                                <div class="select1" id="date1">
                                                        <input type="text" class="datepicker" id="from" value="<?php echo date('Y-m-d');?>" />
                                                        <input name="date_start" type="text" value="<?php echo date('Y-m-d');?>" class="settable date_start" />
                                                </div>
                                                &mdash;
                                                <div class="select1" id="date2">
                                                        <input type="text" class="datepicker" id="to" value="" />
                                                        <input name="date_end" type="text" value="0" class="settable date_end" />
                                                </div>
                                                <div style="display: inline;">
                                                        <input type="checkbox" value="1" name="signal" id="signal" checked="checked" /> no time limit set
                                                </div>
                                        </td></tr>
                                        <tr><td></td><td class="align_left"><input type="checkbox" name="only_link" id="only_link"> Make the collection accessible only from a direct link</td></tr>

                                        <tr id="add_link"><td></td><td class="add_link"><a href="#">Add a website, photographs or video</a></td></tr>
                                        <tr class="add_tr add_tr_closed"><td class="namepad_td">Website address:</td><td class="inp pad_td"><input name="url" type="text" id="url" /></td></tr>
                                        <tr class="add_tr add_tr_closed"><td>Youtube video:</td><td class="inp"><input name="video" type="text" id="video" /></td></tr>
                                        <tr class="add_tr add_tr_closed">
                                        <td>Photographs:</td>
                                        <td class="add_photo"><a href="#">add a photograph</a></td>
                                        </tr>
                                        <tr><td></td><td>
                                        <div class="photocontainer">                                                    
                                        </div>
                                        </td></tr>
                                        <?php if($this->pages != '') : ?>
                                        <tr id="add_link2"><td></td><td class="add_link2"><a href="#">Change owner of the collection</a></td></tr>
                                        <tr class="add_tr2 add_tr2_closed">
                                            <td>Published by:</td>
                                            <td class="inp">
                                                <select name="who" type="text" id="who">
                                                    <option value="<?php echo $this->user['Uid'];?>"><?php echo $this->user['Username'];?></option>
                                                    <?php foreach($this->pages as $v) : ?>
                                                    <option value="<?php echo $v['page_id'];?>"><?php echo $v['name'];?></option>
                                                    <?php endforeach; ?>
                                                </select>
                                            </td>
                                        </tr>
                                        <?php endif; ?>
                                        <tr class="add_tr2 add_tr2">
                                            <td>For who:</td>
                                            <td class="inp">
                                                <select id="groupselect">
                                                    <option value="0">For everyone</option>
                                                    <option value="1">For friends</option>
                                                </select>
                                            </td>
                                        </tr>
                                </table>

                        </div>

                        <div class="about_friends">
                                <div class="title3">To friends</div>
                                <div class="friends"><span>0</span> friends are selected (<a href="#">Select</a>)</div>
                        </div>

                        <div class="about_money">
                                <div class="title3">About money</div>
                                <div>What amount would you like to appear? Choose from the options:</div>
                                <div id="cash_variants">
                                        <ul>
                                                <li class="curr"><img src="/i/settings-all-32.png" alt="Everything on the account" /> <div>Account total</div></li>
    <!--							<li><img src="/i/settings-date-32.png" alt="Only for the time of the collection" /> <div>Collected за время акции</div></li>-->
                                                <li><img src="/i/settings-campaign-32.png" alt="Only using the app" /> <div>Total for this collection</div></li>
                                        </ul>
                                        <input name="source" type="text" value="0" />
                                </div>
                                <div class="cv_info cv_show">
                                Show how much money is in your Yandex.Money account.  You can also show how much money you have raised using other means.</div>
    <!--					<div class="cv_info">
                                Показываем, сколько денег пришло на счет за определенный срок. Вы также можете указать сумму, которую собрали другими способами. </div>-->
                                <div class="cv_info">
                                Count only money raised for this collection via the app.  You can also show how much money you have raised using other means.</div>
                                <table>

    <!--						<tr class="mbegin tr_closed"><td class="period">Начать отсчет с:</td><td class="inp">
                                                <div class="select1" id="date3">
                        <input type="text" class="datepicker" value="<?php echo date('Y-m-d');?>" />
                                                        <input name="ymfromdate" type="text" value="<?php echo date('Y-m-d');?>" class="settable ymfromdate" />
                                                </div>
                                        </td></tr>-->
                                        <tr><td>You already have:</td>
                                        <td class="inp">
                                        <input name="current_sum" type="text" id="current_sum" value="0" />
                                        <p>rub. (a total of – <span><?php echo $this->balance?> rub.</span>)</p>
                                        </td>
                                        </tr>
                                        <tr class="grouptr">
                                                <td>Target:</td>
                                                <td class="inp"><input name="required_sum_group" id="required_sum_group" type="text" value="" /> <p>rub.</p></td>
                                        </tr>
                                        <tr><td>Amount remaining:</td>
                                        <td class="inp"><input name="required_sum" id="required_sum" type="text" value="" /> <p>rub.</p></td></tr>
                                </table>
                        </div>

                        <input type="hidden" value="N" name="draft" id="draft" />
                        <input type="hidden" value="0" name="group" id="group" />
                        <div class="new_action_buttons"><button type="submit" class="button2" name="public" id="publicbutton">Publish</button>
                            <a href="#" class="button1" id="draftbutton">Save draft</a>
                        </div>
                </form>
        </div>
        <div class="right">
                <div class="mini_block">
                        <div class="mini_block_inner">
                                <div class="mb_timer"></div>
                                <div class="mb_title"><a href="#"></a> <div>
                                <a href="<?php echo $this->user['Userurl']?>" target="_blank"><?php echo mb_strlen($this->user['Username'], "UTF-8")<=18 ? $this->user['Username'] : 
                                        mb_substr($this->user['Firstname'], 0, 1, "UTF-8").'. '.$this->user['Lastname']?></a></div></div>
                                <div class="mb_money_line"><div style="width:0%; background-position:0 -520px;"><div></div></div></div>
                                <div class="mb_collected"></div>
                        </div>
                </div>
        </div>
</div>
</div>

<?php if($this->pages != '') : ?>
<div style="display:none">
    <div id="<?php echo $this->user['Uid'];?>">		
        <a href="<?php echo $this->user['Userurl'] ?>" target="_blank">
            <?php echo mb_strlen($this->user['Username'], "UTF-8") <= 18 ? $this->user['Username'] :
                    mb_substr($this->user['Firstname'], 0, 1, "UTF-8") . '. ' . $this->user['Lastname']; ?>
        </a>
    </div>
    <?php foreach($this->pages as $v) : ?>
    <div id="<?php echo $v['page_id'];?>">		
        <a href="<?php echo 'http://www.facebook.com/' . $v['username'] ?>" target="_blank">
            <?php echo mb_strlen($v['name'], "UTF-8") <= 50 ? $v['name']
                    : mb_substr($v['name'], 0, 49, "UTF-8") . "…"; ?>
        </a>
    </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<div class="listphoto">
    <p>Photographs selected must be from albums available to all users.</p>
    <div id="file-uploader-demo1">		
        <noscript>			
            <p>Please enable JavaScript to use file uploader.</p>
                    or put a simple form for upload here 
        </noscript>         
    </div>
    <div class="morephoto"><a href="#">More...</a></div>
    <div id="photos"></div>
</div>

<div class="friendlist">
<p>Select friends for a collection</p>

</div>