security:
    encoders:
        Vmeste\SaasBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            entity: { class: VmesteSaasBundle:User }

    firewalls:

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            form_login:
                login_path: login
                check_path: login_check
                failure_path: /login
                success_handler: authentication_handler
                provider: users
#                always_use_default_target_path: true

            logout:
                path:   logout
                #target: /
                success_handler: logout_handler

            anonymous: true
            #http_basic:
            #    realm: "Secured Demo Area"



    access_control:
         - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/forgot_pass, role: S_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/logout, roles: { ROLE_USER, ROLE_ADMIN } }
         - { path: ^/customer, role: ROLE_USER }
         - { path: ^/admin, role: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
