<?php 
$monthNamesForInput = array('января','февраля','марта','апреля','мая','июня','июля','августа','сентября','октября','ноября','декабря');
?>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/create_edit.js')?>'></script>
<link href="<?php echo $this->baseUrl('css/fileuploader.css') ?>" rel="stylesheet" type="text/css">
<script src="<?php echo $this->baseUrl('js/fileuploader.js') ?>" type="text/javascript"></script>
<script>
/* ABOUT MONEY */
var bal = <?php echo $this->balance?>;
var action_id = '<?php echo $this->action['id']?>';
var action_pid = '<?php echo $this->action['page_id']?>';
var page_id = 0;
var uid = '<?php echo $this->uid;?>';
var current_user = <?php echo json_encode($this->user)?>;
//var previousUrl = '<?php echo $this->hostUrl; ?>' + '/actions/index';
var curbal = 0;
var adminEdit = 0;
var months = ['января','февраля','марта','апреля','мая','июня','июля','августа','сентября','октября','ноября','декабря'];

$(function() {

     VK.callMethod('showInstallBox');
     <?php if(!$this->vk_user_settings&2&&!$this->view->vk_user_settings&4) : ?>
     VK.addCallback('onApplicationAdded', function() {

       VK.callMethod('showSettingsBox', 2+4);
     });
     <?php endif; ?>

    /* select variant */
    $('#cash_variants li').each(function(CVI) {

    	if($(this).hasClass('curr') && CVI==0) {
    		if($('#required_sum').val()>0) {
        		setrightwreq();
    		} else {
    			setrightworeq();
    		}
    	}

        $(this).click(function() {
            $('#cash_variants li').removeClass('curr');
            $(this).addClass('curr');
            $('#cash_variants input').attr('value',CVI);
            /* show/hide hidden rows */
            if(CVI==0||CVI==2) { $('.mbegin').addClass('tr_closed'); }
            if(CVI==1) { $('.mbegin').removeClass('tr_closed'); }
            $('.cv_info').removeClass('cv_show'); $('.cv_info').eq(CVI).addClass('cv_show');
            if(CVI==0) {
            	sumbalance();
            	if(!isNaN(toHumanNumber($('#required_sum').val())) && !isNaN(toHumanNumber($('#current_sum').val()))) {
	            	if(toHumanNumber($('#required_sum').val())>0) {
	            		setrightwreq();
	        		} else {
	        			setrightworeq();
	        		}
            	} else if (isNaN(toHumanNumber($('#required_sum').val())) && !isNaN(toHumanNumber($('#current_sum').val()))) {
            		setrightworeq();
            	} else if (isNaN(toHumanNumber($('#required_sum').val())) && isNaN(toHumanNumber($('#current_sum').val()))) {
            		setrightWoReqWBal();
            	} else if (!isNaN(toHumanNumber($('#required_sum').val())) && isNaN(toHumanNumber($('#current_sum').val()))) {
            		setrightWithReqWoBal();
            	}
            } else if(CVI==2) {
            	sumbalance();
            } else {
            	sumbalance();
            }
            var hframe = $('.wrapper').height(); 
        	VK.callMethod('resizeWindow', 770, hframe);
        });
    });

});

//function sumbalance()
//{
//	var newbal = bal;
//	if(!isNaN(toHumanNumber($('#current_sum').val())) && $('#cash_variants input').attr('value')==0) {
//		newbal = toHumanNumber($('#current_sum').val())+bal;
//	} else if(!isNaN(toHumanNumber($('#current_sum').val())) && $('#cash_variants input').attr('value')!=0) {
//		newbal = toHumanNumber($('#current_sum').val());
//	}
//	if($('#cash_variants input').attr('value')!=0) {
//		$('.about_money td.inp p').first().html('руб.');
//	} else {
//		$('.about_money td.inp p').first().html('руб. (всего &ndash; <span>' + formatMoney(newbal) + ' руб.</span>)');
//	}
//}

//function checkname()
//{
//	var name = $('#name').val();
//
//	$.ajax({
//        url: checknameAjaxUrl,
//        type: "GET",
//        dataType: "json",
//		data: {
//			name: name
//		},
//        success: function (data) {
//        	if(data == true) {
//        		$('#name').css("border", '1px solid #F00');
//            	goodname = false;
//        	} else {
//        		$('#name').css("border", '1px solid #BDC6D9');
//        		goodname = true;
//        	}
//        }
//	});
//}

//function updateRightBalance()
//{
//	if($('input[name="source"]').val()!='2' && $('input[name="source"]').val()!='1') {
//		curbal = bal;
//	}
//	if(!isNaN(toHumanNumber($('#required_sum').val())) && !isNaN(toHumanNumber($('#current_sum').val()))) {
//		if($('#required_sum').val()>0) {
//    		setrightwreqC();
//		} else {
//			setrightworeqC();
//		}
//	} else if(isNaN(toHumanNumber($('#required_sum').val())) && !isNaN(toHumanNumber($('#current_sum').val()))) {
//		setrightworeqC();
//	} else if(!isNaN(toHumanNumber($('#required_sum').val())) && isNaN(toHumanNumber($('#current_sum').val()))) {
//		setrightWithReqWoBal();
//	} else {
//		setrightWoReqWBalC();
//	}
//}

$(document).ready(function(){
        
//        function vkautopost() {
//                var postfrom = uid;
//                if($('#who :selected').val() != uid) {
//                    postfrom = - $('#who :selected').val();
//                }
//                //console.log(postfrom);
//                VK.api("wall.post", {owner_id: postfrom, message: 'Друзья, поддержите хорошее дело!', from_group: 1, signed: 0},
//                    function(data) {}
//                );
//        }
        $('#draftbutton').click(function(){
		var name = $('#name').val();
		if(name.replace(/\s+/g, '').length==0 || $.trim(name.replace(/(<([^>]+)>)/ig,"")).length==0) {
			$('#name').css("border", '1px solid #F00');
                        goodname = false;
                        return false;
		}
                if(parseInt($('#required_sum').val()) > 1000000000 || parseInt($('#required_sum').val()) < 1) {
                    $('#required_sum').css("border", '1px solid red');
                    return false;
                }
                if(parseInt($('#current_sum').val()) >= parseInt($('#required_sum').val()) ||
                    //не ржать - требования тестера
                    ($('#current_sum').val() == '' && parseInt($('#required_sum').val() == 0))) {
                    $('#current_sum').css("border", '1px solid red');
                    canclick = true;
                    return false;
                }
                if($('#groupselect').val() == 1) {
                    if($(".insertedfriends").length == 0) {
                        $(".friends").css("color", "red");
                        return false;
                    };
                }
		$.ajax({
                    url: checknameAjaxUrl,
                    type: "GET",
                    dataType: "json",
                            data: {
                                    name: name
                            },
                    success: function (data) {
                            if(data == true) {
                                    $('#name').css("border", '1px solid #F00');
                            goodname = false;
                            $('#name').focus();
                            } else {
                                    $('#name').css("border", '1px solid #BDC6D9');
                                    goodname = true;
                                    $('#draft').val('Y');
    //                                vkautopost();
                                    $('#actionform').submit();
                            }
                    }
		});
		return false;
	});
	var canclick = true;
	$('#publicbutton').click(function(){
		//alert('single');
		//$(this).hide();
		if(canclick) {
			canclick = false;
		} else return false;
		var name = $('#name').val();
		if(name.replace(/\s+/g, '').length==0 || $.trim(name.replace(/(<([^>]+)>)/ig,"")).length==0) {
			$('#name').css("border", '1px solid #F00');
                        goodname = false;
                        canclick = true;
                        return false;
		}
                if(parseInt($('#required_sum').val()) > 1000000000 || parseInt($('#required_sum').val()) < 1) {
                    $('#required_sum').css("border", '1px solid red');
                    canclick = true;
                    return false;
                }
                if(parseInt($('#current_sum').val()) >= parseInt($('#required_sum').val()) ||
                    //не ржать - требования тестера
                    ($('#current_sum').val() == '' && parseInt($('#required_sum').val() == 0))) {
                    $('#current_sum').css("border", '1px solid red');
                    canclick = true;
                    return false;
                }
                if($('#groupselect').val() == 1) {
                    if($(".insertedfriends").length == 0) {
                        $(".friends").css("color", "red");
                        canclick = true;
                        return false;
                    };
                }
		$.ajax({
	        url: checknameAjaxUrl,
	        type: "GET",
	        dataType: "json",
			data: {
				name: name
			},
	        success: function (data) {
	        	if(data == true) {
	        		$('#name').css("border", '1px solid #F00');
	            	goodname = false;
	            	$('#name').focus();
	            	canclick = true;
	            	//$(this).show();
	        	} else {
	        		$('#name').css("border", '1px solid #BDC6D9');
	        		goodname = true;
	        		$('#draft').val('N');
//                                vkautopost();
	    			$('#actionform').submit();
	        	}
	        }
		});
		return false;
	});
	$('#publicbutton').dblclick(function(){
		if(canclick) {
			canclick = false;
		} else return false;
		var name = $('#name').val();
		if(name.replace(/\s+/g, '').length==0 || name.replace(/(<([^>]+)>)/ig,"").length==0) {
			$('#name').css("border", '1px solid #F00');
                        goodname = false;
                        canclick = true;
                        return false;
		}
                if(parseInt($('#required_sum').val()) > 1000000000 || parseInt($('#required_sum').val()) < 1) {
                    $('#required_sum').css("border", '1px solid red');
                    canclick = true;
                    return false;
                }
                if(parseInt($('#current_sum').val()) >= parseInt($('#required_sum').val()) ||
                    //не ржать - требования тестера
                    ($('#current_sum').val() == '' && parseInt($('#required_sum').val() == 0))) {
                    $('#current_sum').css("border", '1px solid red');
                    canclick = true;
                    return false;
                }
                if($('#groupselect').val() == 1) {
                    if($(".insertedfriends").length == 0) {
                        $(".friends").css("color", "red");
                        canclick = true;
                        return false;
                    };
                }
		$.ajax({
	        url: checknameAjaxUrl,
	        type: "GET",
	        dataType: "json",
			data: {
				name: name
			},
	        success: function (data) {
	        	if(data == true) {
	        		$('#name').css("border", '1px solid #F00');
	            	goodname = false;
	            	$('#name').focus();
	            	canclick = true;
	        	} else {
	        		$('#name').css("border", '1px solid #BDC6D9');
	        		goodname = true;
	        		$('#draft').val('N');
//                                vkautopost();
	    			$('#actionform').submit();
	        	}
	        }
		});
		return false;
	});

	$('.right').hide();
	var hidden = true;
	var goodname = true;
	var friendsIsLoaded = false;
	$('#name').blur(function(){
		var name = $(this).val();
		checkname();
                
                if(name.length<=52) {
			$('.right .mb_title a').first().html(name);
		} else {
			$('.right .mb_title a').first().html(name.slice(0, 52) + '…');
		}
                if($('.right .mb_title a').width() > $('.right .mb_title').width()) {
                        if($('.right .mb_title a').width() > $('.right .mb_title').width()) {
                            tmparr = name.split(' ');
                            ind = 0;
                            for(i = 1; i < tmparr.length; i++) {
                                if(tmparr[i].length > tmparr[i-1].length) {
                                    ind = i;                                
                                }
                            }
                            keyLength = $('.right .mb_title a').width() / tmparr[ind].length;
                            for(i = 0; i < tmparr.length; i++) {
                                if(tmparr[i].length * keyLength > $('.right .mb_title').width()) {
                                    keyNums = Math.round((tmparr[i].length * keyLength - $('.right .mb_title').width()) / keyLength);
                                    tmparr.length = i+1;
                                    tmpstr = tmparr.join(' ');
                                    $('.right .mb_title a').first().html(tmpstr.substring(0, tmpstr.length - keyNums - 4) + '…');
                                    break;
                                }                                                        
                            }
                        }
                }

		settime();
		if (hideRight()) hidden = true;
		updateRightBalance();
	});

	$('#name').keyup(function(){
		if(hidden) {
			showRight();
			hidden = false;
		}
		var name = $(this).val();
		checkname();
                $('.right .mb_title a').first().html(name);
                
                if($('.right .mb_title a').width() > $('.right .mb_title').width()) {
                        if($('.right .mb_title a').width() > $('.right .mb_title').width()) {
                            tmparr = name.split(' ');
                            ind = 0;
                            for(i = 1; i < tmparr.length; i++) {
                                if(tmparr[i].length > tmparr[i-1].length) {
                                    ind = i;                                
                                }
                            }
                            keyLength = $('.right .mb_title a').width() / tmparr[ind].length;
                            for(i = 0; i < tmparr.length; i++) {
                                if(tmparr[i].length * keyLength > $('.right .mb_title').width()) {
                                    keyNums = Math.round((tmparr[i].length * keyLength - $('.right .mb_title').width()) / keyLength);
                                    tmparr.length = i+1;
                                    tmpstr = tmparr.join(' ');
                                    $('.right .mb_title a').first().html(tmpstr.substring(0, tmpstr.length - keyNums - 4) + '…');
                                    break;
                                }                                                        
                            }
                        }
                } else {
                        if(name.length<=52) {
                                $('.right .mb_title a').first().html(name);
                        } else {
                                $('.right .mb_title a').first().html(name.slice(0, 52) + '…');
                        }
                }

		settime();
		if (hideRight()) hidden = true;
		updateRightBalance();
	});
        $('#date1 .datepicker, #date2 .datepicker').change(function() {
            settime();
        });
        $('#date2 .datepicker').click(function() {
            if($('#signal:checked').length) {
                    $('#signal').prop('checked', false);
            }
	});
        
        var tmp = new Date();
        var date1 = $('#date1 .datepicker').datepicker("getDate");
        $('#date1 .datepicker').datepicker("option", "minDate", tmp);
        var textdate = tmp.getDate() + ' ' + months[tmp.getMonth()];
        $('#from').val(textdate);
        
        tmp = $.datepicker.formatDate('yy-mm-dd', new Date());
        date1.setDate(date1.getDate() + 1);
        $('#date2 .datepicker').datepicker("option", "minDate", date1 < tmp ? date1 : tmp);
        
        $('#signal').change(function() {
            if($('#date2 .datepicker').val().length != 0) {
                settime();
            }
            var hframe = $('.wrapper').height(); 
            VK.callMethod('resizeWindow', 770, hframe);
        });
	$('#current_sum').keyup(function(){
		if(hidden) {
			showRight();
			hidden = false;
		}
		updateRightBalance();
		settime();
		sumbalance();
		if (hideRight()) hidden = true;
	});
	$('#required_sum').keyup(function(){
		if(hidden) {
			showRight();
			hidden = false;
		}

		if($('.insertedfriends').size()>0) {
			$('#required_sum_group').val(Math.round(100*($(this).val()/($('.insertedfriends').size()+1)))/100);
		}
		
		updateRightBalance();
		settime();
		sumbalance();
		if (hideRight()) hidden = true;
	});

	$('#required_sum_group').keyup(function(){
		if(hidden) {
			showRight();	
			hidden = false;		
		}
		
		if($('.insertedfriends').size()>0) {
			$('#required_sum').val(Math.round(100*($(this).val()*($('.insertedfriends').size()+1)))/100);
		}
		
		updateRightBalance();
		sumbalance();
		settime();
		if (hideRight()) hidden = true;
	});

	$('#required_sum').click(function(){
		if($('#required_sum').val()==0) {
			$('#required_sum').val('');
		}
	});
	$('#current_sum').blur(function(){
		if($('#current_sum').val()=='') {
			$('#current_sum').val('0');
		}
	});
	$('#current_sum').click(function(){
		if($('#current_sum').val()==0) {
			$('#current_sum').val('');
		}
	});

	jQuery.validator.addMethod("number", function(value, element) {
		if(/^\d*[\.|\,|\s]*\d+$/.test(value) || value=='') {
			$(element).css("border", '1px solid #BDC6D9');
			return true;
		} else {
			return false;
		}
	}, '');
        
	var formValidator = $('#actionform').validate({
            errorPlacement: function(error, element) {
                    element.css("border", 'red 1px solid');
            },
            rules: {
                'video': {
                    url: true
                },
                'current_sum': {
                    number: true
                },
                'required_sum': {
                    number: true
                },
                'required_sum_group': {
                    number: true
                }
            }
        });

	$('.choose_end_block').hide();
	/* choose end date */
	$('.choose_end a').click(function() {
		$(this).parent().hide();
		$('.choose_end_block').show();
		$('.remove_end').show();
		var hframe = $('.wrapper').height(); 
                VK.callMethod('resizeWindow', 770, hframe);
                return false;
	});
	/* remove end date */
	$('.remove_end').click(function() {
		$(this).hide();
		$('.choose_end_block').hide();
		$('.choose_end').show();
		$('input.date_end').val(0);
                $('#date1 .datepicker').datepicker("option", "maxDate", null);
                
                var months = ['января','февраля','марта','апреля','мая','июня','июля','августа','сентября','октября','ноября','декабря'];
                var datestamp = $.datepicker.parseDate('yy-mm-dd', $('input.date_start').val());
                var textdate = datestamp.getDate() + ' ' + months[datestamp.getMonth()];
                $('#from').val(textdate);
		var hframe = $('.wrapper').height(); 
                VK.callMethod('resizeWindow', 770, hframe);
                return false;
	});

	/* add photo */
        $('.selectphoto').live('click', function(){
            if($(this).attr('class') == 'selectphoto selected') {
                    $(this).removeClass('selected');
                    //alert($('.photocontainer').find('input[value="'+$(this).attr('pid').replace('photo', '')+'"]').length);
                    //$('.photocontainer').find('input[value="'+$(this).attr('pid').replace('photo', '')+'"]').remove();
                    $('.listphoto a[pid="'+$(this).attr('pid')+'"]').removeClass('selected');
                    $('.photocontainer').find('#'+$(this).attr('pid').replace('photo', 'img')).remove();
            } else {
                    $(this).addClass('selected');
                    $('.listphoto a[pid="'+$(this).attr('pid')+'"]').addClass('selected');
                    $('.photocontainer').append('<table id="'+$(this).attr('pid').replace('photo', 'img')+'"><tr><td><a href="#" class="del_photo"></a><input type="hidden" name="photo['+fileCounter+']" value="'+$(this).attr('pid').replace('photo', '')+'" /><img src="'+$(this).find('img').attr('src')+'" valign="middle"/></td></tr></table>');
                fileCounter++;
            }
            var hframe = $('.wrapper').height(); 
            VK.callMethod('resizeWindow', 770, hframe);
        });

	$('.del_photo').live('click', function() {
		var table_id = $(this).siblings('input').val();
		$('.listphoto a[pid=photo'+table_id+']').removeClass('selected');
            $('table#img'+table_id).remove();
            var hframe = $('.wrapper').height(); 
            VK.callMethod('resizeWindow', 770, hframe);
            return false;
        });

//	var offset = 0;
//	$('.add_photo a').click(function() {
//		$(this).fb_popup({
//			content_container: '.listphoto',
//			//content:'',
//			title: 'Выберите фото',
//			popup_id: 'popup_tpl',
//			width: 760,
//			height: 450,
//			overflow: 'auto'
//		});
//    if(loadPhotos) {
//		  $.ajax({
//              url: getphotoAjaxUrl,
//              type: "POST",
//              dataType: "json",
//			  data: {
//				  offset: offset
//			  },
//              success: function (data) {
//            	  if(data.length > 0) {
//                	  //alert(data);
//            		  $('.morephoto').remove();
//                	  jQuery.each(data, function(i, element){
//            			  $('.p_pad').append('<a class="selectphoto" pid="photo'+element['pid']+'" href="#"><img src="'+element['src']+'" /></a>');
//            			  $('.listphoto').append('<a class="selectphoto" pid="photo'+element['pid']+'" href="#"><img src="'+element['src']+'" /></a>');
//                	  });
//                    /*
//                	  $('.p_pad').append('<div class="morephoto"><a href="#">Еще...</a></div>');
//                	  $('.listphoto').append('<div class="morephoto"><a href="#">Еще...</a></div>');
//                    */
//            		  offset = 50;
//            		  if(data.length<50) {
//            			  $('.morephoto').remove();
//            		  }
//            		  //
//            	  } else {
//                	  $('.morephoto').remove();
//            	  }
//              }
//    	  });
//        loadPhotos = false;
//    }
//        return false;
//    });
//	$('.morephoto').live("click", function(){
//    	$.ajax({
//            url: getphotoAjaxUrl,
//            type: "POST",
//            dataType: "json",
//			data: {
//				offset: offset
//			},
//            success: function (data) {
//            	if(data.length > 0) {
//                	//alert(data);
//            		$('.morephoto').remove();
//                	jQuery.each(data, function(i, element){
//            			$('.p_pad').append('<a class="selectphoto" pid="photo'+element['pid']+'" href="#"><img src="'+element['src']+'" /></a>');
//            			$('.listphoto').append('<a class="selectphoto" pid="photo'+element['pid']+'" href="#"><img src="'+element['src']+'" /></a>');
//                	});
//                	$('.p_pad').append('<div class="morephoto"><a href="#">Еще...</a></div>');
//                	$('.listphoto').append('<div class="morephoto"><a href="#">Еще...</a></div>');
//            		offset = offset+50;
//            		if(data.length<50) {
//            			$('.morephoto').remove();
//            		}
//
//            	} else {
//                	$('.morephoto').remove();
//            	}
//            	
//            }
//    	});
//		return false;
//    });

	//alert($.datepicker.parseDate('d MM', '<?php echo date('Y-m-d');?>', {monthNames: $.datepicker.regional['ru'].monthNamesForInput}));

//	$('.tabs ul li a.simple-action').live("click", function(){
//                $('.tabs ul li.simple-action').addClass('current_link');
//                $('.tabs ul li.for-friends').removeClass('current_link');
//                $('.tabs ul li.for-friends').html('<a href="#" class="for-friends"><span class="tl"><span class="tr">Новая акция для друзей</span></span></a>');
//                $('#group').val(0);
//                $('.about_friends, .grouptr').hide();
//		$(this).replaceWith('<span>' + $(this).html() + '</span>');		 
//		VK.callMethod('resizeWindow', 770, $('.wrapper').height());
//		return false;
//        });
//
//        $('.tabs ul li a.for-friends').live("click", function(){
//                $('.tabs ul li.for-friends').addClass('current_link');
//                $('.tabs ul li.simple-action').removeClass('current_link');
//                $('.tabs ul li.simple-action').html('<a href="#" class="simple-action"><span class="tl"><span class="tr">Новая акция</span></span></a>');
//                $('#group').val(1);
//                $('.about_friends, .grouptr').show();
//                $(this).replaceWith('<span>' + $(this).html() + '</span>');
//                VK.callMethod('resizeWindow', 770, $('.wrapper').height());
//                return false;
//        });

        $('.friends a').live('click', function(){
            $(this).parent().css("color", "#666666");
            $(this).fb_popup({
                            content_container: '.friendlist',
                            //content:'',
                            title: 'Выберите друзей',
                            popup_id: 'popup_tpl',
                            width: 530,
                            height: 450,
                            overflow: 'auto'
                    });
            if(!friendsIsLoaded) {
                    VK.api('friends.get',{fields: 'uid, first_name, last_name'},function(data) {
                    if (data.response) { 
                            var links = '';
                            if(data.response.length > 0) {
                            jQuery.each(data.response, function(i, element){
                                    links = '<table><tr><td>'+element['first_name']+' '+element['last_name']+'</td><td class="friendcheckbox">' + '<input type="checkbox" id="friend'+element['uid']+'" value="'+element['uid']+'"/></td></tr></table>';
                                            $('.p_pad').append(links);
                                            $('.friendlist').append(links);
                            });
                            friendsIsLoaded = true;

                            }
                    }
                            });
            }
            VK.callMethod('resizeWindow', 770, $('.wrapper').height());
            return false;
        });
    
        var checkedfriends;
        $('.friendcheckbox input').live('click', function(){
            if($(this).is(':checked')) {
                    checkedfriends = '<input type="hidden" value="'+$(this).val()+'" name="friends[]" id="checkedfriend'+$(this).val()+'" class="insertedfriends"/>';
                    $(checkedfriends).appendTo('#actionform');
                    $('#friend'+$(this).val()).attr('checked', 'checked');
            } else {
                $("#checkedfriend"+$(this).val()).remove();
                $('#friend'+$(this).val()).attr('checked', false);
            }
            $('.friends span').html($('.insertedfriends').size());
            if($('.insertedfriends').size()>0 && $('#required_sum').val()>0) {
                            $('#required_sum_group').val(Math.round(100*($('#required_sum').val()/($('.insertedfriends').size()+1)))/100);
                    }
            if($('.insertedfriends').size()==0) {
                $('#required_sum_group').val($('#required_sum').val());
            }
        });  
	
	var hframe = $('.wrapper').height(); 
	VK.callMethod('resizeWindow', 770, hframe);

});

//$(document).ajaxStart(function(){
//	$('.morephoto').append('<span class="loading"></span>');
//}).ajaxStop(function(){
//	$('.morephoto span').remove();
//});
</script>

<div class="header">
	<a  href="<?php echo $this->appurlorigin?>" target="_top" class="logo"></a>
	<div class="header_links">
		<div id="vk_like"></div>
		<script type="text/javascript">
		VK.Widgets.Like("vk_like", {type: "button", 
			pageUrl: '<?php echo $this->appurlorigin?>', 
			pageDescription: '<?php echo $this->appdesc?>', 
			pageTitle: '<?php echo $this->appname?>',
			text: '<?php echo $this->appdesc?>',
			verb: 1});
		</script>
	</div>
</div>

<div class="tabs">
	<ul>
		<li>
			<a href="/actions"><span class="tl"><span class="tr">Все акции</span></span></a>
		</li>
		<li>
			<a href="/actions/my"><span class="tl"><span class="tr">Мои акции</span></span></a>
			</li>
		<li>
			<a href="/actions/account"><span class="tl"><span class="tr">Мой счет</span></span></a>
		</li>
                <?php if($this->admin) {?> 
		<li>
			<a href="/actions/adminstat"><span class="tl"><span class="tr">Статистика</span></span></a>
		</li>
		<li>
			<a href="/actions/duplicates"><span class="tl"><span class="tr">Дубликаты</span></span></a>
		</li>
		<li>
			<a href="/actions/admins"><span class="tl"><span class="tr">Админы</span></span></a>
		</li>
		<?php } ?>
<!--		<li class="current_link simple-action">
			<span><span class="tl"><span class="tr">Новая акция</span></span></span>
		</li>
		<li class="for-friends">
			<a href="#" class="for-friends"><span class="tl"><span class="tr">Новая акция для друзей</span></span></a>
		</li>-->
	</ul>
</div>

<div class="content">

<div class="admin">

		<div class="title3">Описание новой акции</div>

		<div class="left">

			<form action="" method="post" enctype="multipart/form-data" id="actionform">

				<div class="new_action">

					<table id="edit_table">
						<tr><td>На что собираете:</td><td class="inp"><input name="name" maxlength="60" type="text" id="name"/></td></tr>

						<tr><td>Подробное описание:</td><td class="inp"><textarea name="description" cols="" rows=""></textarea></td></tr>

						<tr><td>Метки:</td><td class="inp"><input name="tags" type="text" /></td></tr>

						<tr class="period"><td>Дата начала:</td><td class="inp">
							<div class="select1" id="date1">

                                <input type="text" class="datepicker" id="from" value="<?php echo date('j '.$monthNamesForInput[date('n')-1]);?>" />
								<input name="date_start" type="text" value="<?php echo date('Y-m-d');?>" class="settable date_start" />
							</div>
							<div class="choose_end">
								<a href="#">Указать дату окончания</a>
							</div>
						</td></tr>
						<tr class="period choose_end_block"><td>Дата окончания:</td><td class="inp">
							<div>
								<div class="select1" id="date2">
	                                <input type="text" class="datepicker" id="to" value="" />
									<input name="date_end" type="text" value="0" class="settable date_end" />
								</div>
								<a href="#" class="remove_end">Удалить</a>
								<div style="display: none;">
									<input type="checkbox" value="1" name="signal" id="signal" checked="checked" /> бессрочно
								</div>
							</div>
						</td></tr>
                                                <tr><td></td><td class="align_left"><input type="checkbox" name="only_link" id="only_link"> Сделать акцию видимой только по прямой ссылке</td></tr>

						<tr id="add_link"><td></td><td class="add_link"><a href="#">Добавить сайт, фотографии или видео</a></td></tr>
						<tr class="add_tr add_tr_closed"><td class="namepad_td">Адрес сайта:</td><td class="inp pad_td"><input name="url" type="text" id="url" /></td></tr>
						<tr class="add_tr add_tr_closed"><td>Видео на YouTube:</td><td class="inp"><input name="video" type="text" id="video" /></td></tr>
						<tr class="add_tr add_tr_closed">
						<td>Фотографии:</td>
                                                <td class="add_photo">
                                                    <a href="#">добавить фотографию</a>
                                                    <!--служебные поля-->
                                                    <input type="hidden" name="urlh" id="urlh" />
                                                    <input type="hidden" name="actionnameh" id="actionnameh" /></td>
						</tr>
						<tr><td></td><td>
						<div class="photocontainer"></div>
						</td></tr>
                                                <tr class="add_tr2 add_tr2">
                                                    <td>Для кого:</td>
                                                    <td class="inp">
                                                        <select id="groupselect">
                                                            <option value="0">Для всех</option>
                                                            <option value="1" <?php if($this->action['group'] == 1) echo "selected";?>>Для друзей</option>
                                                        </select>
                                                    </td>
                                                </tr>
					</table>

				</div>

				<div class="about_friends">
					<div class="title3">Про друзей</div>
					<div class="friends">Выбрано <span>0</span> друзей (<a href="#">выбрать</a>)</div>
				</div>

				<div class="about_money">

					<div class="title3">Про деньги</div>
					<div class="about_money_inner">
						<div>Какую сумму показывать на информере? Выберите нужный вариант:</div>

						<div id="cash_variants">
							<ul>
								<li class="curr"><img src="/i/settings-all-32.png" alt="Всего на счету" /> <div>Всего на счету</div></li>
<!--								<li><img src="/i/settings-date-32.png" alt="Собрано за время акции" /> <div>Собрано<br />за время акции</div></li>-->
								<li><img src="/i/settings-campaign-32.png" alt="Собрано для этой акции" /> <div>Собрано<br />для этой акции</div></li>
							</ul>
							<input name="source" type="text" value="0" />
						</div>
						<div class="cv_info cv_show">Показываем, сколько всего Яндекс.Денег на вашем счету. Вы также можете указать сумму, которую собрали другими способами.</div>
<!--						<div class="cv_info">Показываем, сколько денег пришло на счет за определенный срок. Вы также можете указать сумму, которую собрали другими способами.</div>-->
						<div class="cv_info">Учитываем только деньги, поступившие на эту акцию через приложение. Вы также можете указать сумму, которую собрали другими способами.</div>
					</div>
					<table>

<!--						<tr class="mbegin tr_closed"><td class="period">Начать отсчет с:</td><td class="inp">
							<div class="select1" id="date3">
                                <input type="text" class="datepicker" value="<?php echo date('j '.$monthNamesForInput[date('n')-1]);?>" />
								<input name="ymfromdate" type="text" value="<?php echo date('Y-m-d');?>" class="settable ymfromdate" />
							</div>
						</td></tr>-->
						<tr><td>У вас уже есть:</td>
						<td class="inp">
						<input name="current_sum" type="text" id="current_sum" value="0" />
						<p>руб. (всего – <span><?php echo $this->balance?> руб.</span>)</p>
						</td>
						</tr>
						<tr class="grouptr">
							<td>Скидываемся по:</td>
							<td class="inp"><input name="required_sum_group" id="required_sum_group" type="text" value="" /> <p>руб.</p></td>
						</tr>
						<tr><td>Всего нужно собрать:</td>
						<td class="inp"><input name="required_sum" id="required_sum" type="text" value="" /> <p>руб.</p></td></tr>
					</table>
				</div>
				<input type="hidden" value="0" name="group" id="group" />
				<input type="hidden" value="N" name="draft" id="draft" />
				<div class="new_action_buttons"><a href="#" class="button2" id="publicbutton">Опубликовать</a> 
                                    <a href="#" class="button1" id="draftbutton">Сохранить черновик</a>
<!--                                    <a href="#" class="button1" id="canselbutton">Отменить</a>-->
                                </div>
			</form>
		</div>
		<div class="right">
			<div class="mini_block">
				<div class="mini_block_inner">
					<div class="mb_timer"></div>
					<div class="mb_title"><a href="#"></a> <div>
					<a href="<?php echo $this->user['Userurl']?>" target="_blank"><?php echo mb_strlen($this->user['Username'], "UTF-8")<=18 ? $this->user['Username'] :
						mb_substr($this->user['Firstname'], 0, 1, "UTF-8").'. '.$this->user['Lastname']?></a></div></div>
					<div class="mb_money_line"><div style="width:0%; background-position:0 -520px;"><div></div></div></div>
					<div class="mb_collected"></div>
				</div>
			</div>
		</div>
</div>
</div>

<div id="tmp_div" style="display:none"></div>

<div class="listphoto">
    <p>Фотографии должны быть в общедоступных альбомах.</p>
    <div id="file-uploader-demo1">		
        <noscript>			
            <p>Please enable JavaScript to use file uploader.</p>
                    or put a simple form for upload here 
        </noscript>         
    </div>
    <div id="photos"></div>
</div>

<div class="friendlist">
    <p>Выберите друзей для акции</p>
</div>