<?php 
$monthNamesForInput = array('января','февраля','марта','апреля','мая','июня','июля','августа','сентября','октября','ноября','декабря');
?>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/create_edit.js')?>'></script>
<link href="<?php echo $this->baseUrl('css/fileuploader.css') ?>" rel="stylesheet" type="text/css">
<script src="<?php echo $this->baseUrl('js/fileuploader.js') ?>" type="text/javascript"></script>
<script>
/* ABOUT MONEY */

var bal = <?php echo $this->balance?>;
var action_id = '<?php echo $this->action['id']?>';
var action_pid = '<?php echo $this->action['page_id']?>';
var action_user = '<?php echo $this->action['user_id']?>';
var page_id = '<?php echo $this->pages['page_id']?>';
var uid = '<?php echo $this->uid;?>';
var current_user = <?php echo json_encode($this->user)?>;
var previousUrl = '<?php echo $this->hostUrl; ?>' + '/index/index?app_data=' + action_id;
var curbal = 0;
var adminEdit = <?php echo $this->adminEdit; ?>;
if(adminEdit == true) {
    var adminPages = <?php echo json_encode($this->adminPages)?>;
}
var months = ['января','февраля','марта','апреля','мая','июня','июля','августа','сентября','октября','ноября','декабря'];

$(function() {

    /* select variant */
    $('#cash_variants li').each(function(CVI) {
    	if(($(this).hasClass('curr') && CVI==0)) {        	
        	if($('#required_sum').val()>0) {
        		setrightwreq();
    		} else {
    			setrightworeq();
    		}
    	}
    	sumbalance();
        $(this).click(function() {
            $('#cash_variants li').removeClass('curr');
            $(this).addClass('curr');
            $('#cash_variants input').attr('value',CVI);
            /* show/hide hidden rows */
            if(CVI==0||CVI==1) { $('.mbegin').addClass('tr_closed'); }
//            if(CVI==1) { $('.mbegin').removeClass('tr_closed'); }
            $('.cv_info').removeClass('cv_show'); $('.cv_info').eq(CVI).addClass('cv_show');
            if(CVI==0) {
            	sumbalance();
            	if(!isNaN(toHumanNumber($('#required_sum').val())) && !isNaN(toHumanNumber($('#current_sum').val()))) {
	            	if(toHumanNumber($('#required_sum').val())>0) {
	            		setrightwreq();
	        		} else {
	        			setrightworeq();
	        		}
            	} else if (isNaN(toHumanNumber($('#required_sum').val())) && !isNaN(toHumanNumber($('#current_sum').val()))) {
            		setrightworeq();
            	} else if (isNaN(toHumanNumber($('#required_sum').val())) && isNaN(toHumanNumber($('#current_sum').val()))) {
            		setrightWoReqWBal();
            	} else if (!isNaN(toHumanNumber($('#required_sum').val())) && isNaN(toHumanNumber($('#current_sum').val()))) {
            		setrightWithReqWoBal();
            	}
            } else if(CVI==2) {
            	sumbalance();
            } else {
            	sumbalance();
            }
            var hframe = $('.wrapper').height(); 
        	VK.callMethod('resizeWindow', 770, hframe);
        });
    });
});

//function sumbalance()
//{
//	var newbal = bal;
//	if(!isNaN(toHumanNumber($('#current_sum').val())) && $('#cash_variants input').attr('value')==0) {
//		newbal = toHumanNumber($('#current_sum').val())+bal;
//	} else if(!isNaN(toHumanNumber($('#current_sum').val())) && $('#cash_variants input').attr('value')!=0) {
//		newbal = toHumanNumber($('#current_sum').val());
//	}
//	if($('#cash_variants input').attr('value')!=0) {
//		$('.about_money td.inp p').first().html('руб.');
//	} else {
//		$('.about_money td.inp p').first().html('руб. (всего &ndash; <span>' + formatMoney(newbal) + ' руб.</span>)');
//	}
//}

//function checkname()
//{
//	var name = $('#name').val();
//
//	$.ajax({
//        url: checknameAjaxUrl,
//        type: "GET",
//        dataType: "json",
//		data: {
//			name: name,
//			id: action_id
//		},
//        success: function (data) {
//        	if(data == true) {
//        		$('#name').css("border", '1px solid #F00');
//            	goodname = false;
//        	} else {
//        		$('#name').css("border", '1px solid #BDC6D9');
//        		goodname = true;
//        	}
//        }
//	});
//}

//function updateRightBalance()
//{
//	if($('input[name="source"]').val()!='2' && $('input[name="source"]').val()!='1') {
//		curbal = bal;
//	}
//	if(!isNaN(toHumanNumber($('#required_sum').val())) && !isNaN(toHumanNumber($('#current_sum').val()))) {
//		if($('#required_sum').val()>0) {
//    		setrightwreqC();
//		} else {
//			setrightworeqC();
//		}
//	} else if(isNaN(toHumanNumber($('#required_sum').val())) && !isNaN(toHumanNumber($('#current_sum').val()))) {
//		setrightworeqC();
//	} else if(!isNaN(toHumanNumber($('#required_sum').val())) && isNaN(toHumanNumber($('#current_sum').val()))) {
//		setrightWithReqWoBal();
//	} else {
//		setrightWoReqWBalC();
//	}
//}

$(document).ready(function(){
	
	$('#draftbutton').click(function(){
		var name = $('#name').val();
		if(name.replace(/\s+/g, '').length==0 || $.trim(name.replace(/(<([^>]+)>)/ig,"")).length==0) {
			$('#name').css("border", '1px solid #F00');
                        goodname = false;
                        return false;
		}
                if(parseInt($('#required_sum').val()) > 1000000000 || parseInt($('#required_sum').val()) < 1) {
                    $('#required_sum').css("border", '1px solid red');
                    return false;
                }
                if(parseInt($('#current_sum').val()) >= parseInt($('#required_sum').val()) ||
                    //не ржать - требования тестера
                    ($('#current_sum').val() == '' && parseInt($('#required_sum').val() == 0))) {
                    $('#current_sum').css("border", '1px solid red');
                    return false;
                }
                if($('#groupselect').val() == 1) {
                    if($(".insertedfriends").length == 0) {
                        $(".friends").css("color", "red");
                        return false;
                    };
                }
		$.ajax({
	        url: checknameAjaxUrl,
	        type: "GET",
	        dataType: "json",
			data: {
				name: name,
				id: action_id
			},
                        success: function (data) {
                                if(data == true) {
                                        $('#name').css("border", '1px solid #F00');
                                goodname = false;
                                $('#name').focus();
                                } else {
                                        $('#name').css("border", '1px solid #BDC6D9');
                                        goodname = true;
                                        $('#draft').val('Y');
                                        $('#actionform').submit();
                                }
                        }
		});
	});
	$('#publicbutton').click(function(){
		var name = $('#name').val();
		if(name.replace(/\s+/g, '').length==0 || $.trim(name.replace(/(<([^>]+)>)/ig,"")).length==0) {
			$('#name').css("border", '1px solid #F00');
                        goodname = false;
                        return false;
		}
                if(parseInt($('#required_sum').val()) > 1000000000 || parseInt($('#required_sum').val()) < 1) {
                    $('#required_sum').css("border", '1px solid red');
                    return false;
                }
                if(parseInt($('#current_sum').val()) >= parseInt($('#required_sum').val()) ||
                    //не ржать - требования тестера
                    ($('#current_sum').val() == '' && parseInt($('#required_sum').val() == 0))) {
                    $('#current_sum').css("border", '1px solid red');
                    return false;
                }
                if($('#groupselect').val() == 1) {
                    if($(".insertedfriends").length == 0) {
                        $(".friends").css("color", "red");
                        return false;
                    };
                }
		$.ajax({
	        url: checknameAjaxUrl,
	        type: "GET",
	        dataType: "json",
			data: {
				name: name,
				id: action_id
			},
	        success: function (data) {
	        	if(data == true) {
	        		$('#name').css("border", '1px solid #F00');
	            	goodname = false;
	            	$('#name').focus();
	        	} else {
	        		$('#name').css("border", '1px solid #BDC6D9');
	        		goodname = true;
	        		$('#draft').val('N');
	    			$('#actionform').submit();
	        	}
	        }
		});
	});

	<?php
	if($this->endhidden == 0 ) { ?>
	$('.choose_end_block').hide();
	<?php } else { ?>
	$('.choose_end').hide();
	$('.remove_end').show();
	<?php } ?>
	
	$('#date1 .datepicker, #date2 .datepicker').change(function() {
            settime();
        });
        $('#date2 .datepicker').click(function() {
            if($('#signal:checked').length) {
                    $('#signal').prop('checked', false);
            }
        });
        
        //$('#date1 .datepicker').datepicker("option", "defaultDate", '<?php echo $this->starthidden; ?>');
    
        var date1 = $.datepicker.parseDate('yy-mm-dd', $('#date1 .date_start').val());
        date1.setDate(date1.getDate() + 1);
        var tmp = $.datepicker.formatDate('yy-mm-dd', new Date());
        $('#date2 .datepicker').datepicker("option", "minDate", date1 < tmp ? date1 : tmp);
        <?php if($this->endhidden != 0 ) : ?>
            var datestamp = $.datepicker.parseDate('yy-mm-dd', $('input.date_end').val());
            var textdate = datestamp.getDate() + ' ' + months[datestamp.getMonth()];
            $('#to').val(textdate);
        <?php endif; ?>

        $('#signal').change(function() {
            if($('#date2 .datepicker').val().length != 0) {
                settime();
            }
            var hframe = $('.wrapper').height(); 
            VK.callMethod('resizeWindow', 770, hframe);
        });
        
    var goodname = true;
    var friendsIsLoaded = false;
    $('#name').blur(function(){
		var name = $(this).val();
		checkname();
		if(name.length<=52) {
			$('.right .mb_title a').first().html(name);
		} else {
			$('.right .mb_title a').first().html(name.slice(0, 52) + '…');
		}
                if($('.right .mb_title a').width() > $('.right .mb_title').width()) {
                        tmparr = name.split(' ');
                        ind = 0;
                        for(i = 1; i < tmparr.length; i++) {
                            if(tmparr[i].length > tmparr[i-1].length) {
                                ind = i;                                
                            }
                        }
                        keyLength = $('.right .mb_title a').width() / tmparr[ind].length;
                        for(i = 0; i < tmparr.length; i++) {
                            if(tmparr[i].length * keyLength > $('.right .mb_title').width()) {
                                keyNums = Math.round((tmparr[i].length * keyLength - $('.right .mb_title').width()) / keyLength);
                                tmparr.length = i+1;
                                tmpstr = tmparr.join(' ');
                                $('.right .mb_title a').first().html(tmpstr.substring(0, tmpstr.length - keyNums - 4) + '…');
                                break;
                            }                                                        
                        }
                }
		settime();
		updateRightBalance();
	});

	$('#name').keyup(function(){
		var name = $(this).val();
		checkname();
                $('.right .mb_title a').first().html(name);
                
                if($('.right .mb_title a').width() > $('.right .mb_title').width()) {
                        tmparr = name.split(' ');
                        ind = 0;
                        for(i = 1; i < tmparr.length; i++) {
                            if(tmparr[i].length > tmparr[i-1].length) {
                                ind = i;                                
                            }
                        }
                        keyLength = $('.right .mb_title a').width() / tmparr[ind].length;
                        for(i = 0; i < tmparr.length; i++) {
                            if(tmparr[i].length * keyLength > $('.right .mb_title').width()) {
                                keyNums = Math.round((tmparr[i].length * keyLength - $('.right .mb_title').width()) / keyLength);
                                tmparr.length = i+1;
                                tmpstr = tmparr.join(' ');
                                $('.right .mb_title a').first().html(tmpstr.substring(0, tmpstr.length - keyNums - 4) + '…');
                                break;
                            }                                                        
                        }
                } else {
                        if(name.length<=52) {
                                $('.right .mb_title a').first().html(name);
                        } else {
                                $('.right .mb_title a').first().html(name.slice(0, 52) + '…');
                        }
                }
		settime();
		updateRightBalance();
	});
	$('#current_sum').keyup(function(){
		updateRightBalance();
		settime();
		sumbalance();
	});
	$('#required_sum').keyup(function(){
		if($('.insertedfriends').size()>0) {
			$('#required_sum_group').val(Math.round(100*$(this).val()/($('.insertedfriends').size()+1))/100);
		}
		updateRightBalance();
		settime();
		sumbalance();
	});

	$('#required_sum_group').keyup(function(){	
		if($('.insertedfriends').size()>0) {
			$('#required_sum').val(Math.round(100*$(this).val()*($('.insertedfriends').size()+1))/100);
		}		
		updateRightBalance();
		sumbalance();
		settime();
	});
	
	$('#required_sum').click(function(){
		if($('#required_sum').val()==0) {
			$('#required_sum').val('');
		}
	});
	$('#current_sum').blur(function(){
		if($('#current_sum').val()=='') {
			$('#current_sum').val('0');
		}
	});
	$('#current_sum').click(function(){
		if($('#current_sum').val()==0) {
			$('#current_sum').val('');
		}
	});

	jQuery.validator.addMethod("number", function(value, element) {
		if(/^\d*[\.|\,|\s]*\d+$/.test(value) || value=='') {
			$(element).css("border", '1px solid #BDC6D9');
			return true;
		} else {
			return false;
		}
	}, '');

	var formValidator = $('#actionform').validate({
        errorPlacement: function(error, element) {
        	element.css("border", 'red 1px solid');
        },
        rules: {
            'video': {
            	url: true
            },
            'current_sum': {
            	number: true
            },
            'required_sum': {
            	number: true
            },
            'required_sum_group': {
            	number: true
            }
        }
    });
	
	/* choose end date */
	$('.choose_end a').click(function() {
		$(this).parent().hide();
		$('.choose_end_block').show();
		$('.remove_end').show();
		//$('input.date_end').val($('input.date_start').val());
		var hframe = $('.wrapper').height(); 
    	VK.callMethod('resizeWindow', 770, hframe);
    	return false;
	});
	/* remove end date */
	$('.remove_end').click(function() {
		$(this).hide();
		$('.choose_end_block').hide();
		$('.choose_end').show();
		$('input.date_end').val(0);
                $('#date1 .datepicker').datepicker("option", "maxDate", null);
                
                var datestamp = $.datepicker.parseDate('yy-mm-dd', $('input.date_start').val());
                var textdate = datestamp.getDate() + ' ' + months[datestamp.getMonth()];
                $('#from').val(textdate);
		var hframe = $('.wrapper').height(); 
                VK.callMethod('resizeWindow', 770, hframe);
                return false;
	});
	
	/* add photo */
    $('.selectphoto').live('click', function(){
    	if($(this).attr('class') == 'selectphoto selected') {
    		$(this).removeClass('selected');
    		//alert($('.photocontainer').find('input[value="'+$(this).attr('pid').replace('photo', '')+'"]').length);
    		//$('.photocontainer').find('input[value="'+$(this).attr('pid').replace('photo', '')+'"]').remove();
    		$('.listphoto a[pid="'+$(this).attr('pid')+'"]').removeClass('selected');
    		$('.photocontainer').find('#'+$(this).attr('pid').replace('photo', 'img')).remove();
    	} else {
    		$(this).addClass('selected');
    		$('.listphoto a[pid="'+$(this).attr('pid')+'"]').addClass('selected');
        	$('.photocontainer').append('<table id="'+$(this).attr('pid').replace('photo', 'img')+'"><tr><td><a href="#" class="del_photo"></a><input type="hidden" name="photo['+fileCounter+']" value="'+$(this).attr('pid').replace('photo', '')+'" /><img src="'+$(this).find('img').attr('src')+'" valign="middle"/></td></tr></table>');
        	//$('.photocontainer').append('');
            fileCounter++;
    	}
    	var hframe = $('.wrapper').height(); 
    	VK.callMethod('resizeWindow', 770, hframe);
    });

    $('.del_photo').live('click', function() {
		var table_id = $(this).siblings('input').val();
		$('.listphoto a[pid=photo'+table_id+']').removeClass('selected');
    	$('table#img'+table_id).remove();
    	var hframe = $('.wrapper').height(); 
    	VK.callMethod('resizeWindow', 770, hframe);
    	return false;
    });

//	var offset = 0;


//	$('.add_photo a').click(function() {
//		$(this).fb_popup({
//			content_container: '.listphoto',
//			//content:'',
//			title: 'Выберите фото',
//			popup_id: 'popup_tpl',
//			width: 760,
//			height: 450,
//			overflow: 'auto'
//		});
//		if(loadPhotos) {
//			$.ajax({
//	            url: getphotoAjaxUrl,
//	            type: "POST",
//	            dataType: "json",
//				data: {
//					offset: offset,
//					action_id: action_id
//				},
//	            success: function (data) {
//	            	if(data.length > 0) {
//	                	//alert(data);
//	            		$('.morephoto').remove();
//	                	jQuery.each(data, function(i, element){
//	                    	var selected = '';
//	                    	if(element['selected']==1) {
//	                        	selected = ' selected';
//	                    	}
//	            			$('.p_pad').append('<a class="selectphoto'+selected+'" pid="photo'+element['pid']+'" href="#"><img src="'+element['src']+'" /></a>');
//	            			$('.listphoto').append('<a class="selectphoto'+selected+'" pid="photo'+element['pid']+'" href="#"><img src="'+element['src']+'" /></a>');
//	                	});
//	                	$('.p_pad').append('<div class="morephoto"><a href="#">Еще...</a></div>');
//	                	$('.listphoto').append('<div class="morephoto"><a href="#">Еще...</a></div>');
//	            		offset = 50;
//	            		if(data.length<50) {
//	            			$('.morephoto').remove();
//	            		}
//	            	} else {
//	                	$('.morephoto').remove();
//	            	}
//	            }
//	    	});
//		}
//		loadPhotos = false;
//        return false;
//    });
//	$('.morephoto').live("click", function(){
//    	$.ajax({
//            url: getphotoAjaxUrl,
//            type: "POST",
//            dataType: "json",
//			data: {
//				offset: offset,
//				action_id: action_id
//			},
//            success: function (data) {
//            	if(data.length > 0) {
//                	//alert(data);
//            		$('.morephoto').remove();
//                	jQuery.each(data, function(i, element){
//                		var selected = '';
//                    	if(element['selected']==1) {
//                        	selected = ' selected';
//                    	}
//            			$('.p_pad').append('<a class="selectphoto'+selected+'" pid="photo'+element['pid']+'" href="#"><img src="'+element['src']+'" /></a>');
//            			$('.listphoto').append('<a class="selectphoto'+selected+'" pid="photo'+element['pid']+'" href="#"><img src="'+element['src']+'" /></a>');
//                	});
//                	$('.p_pad').append('<div class="morephoto"><a href="#">Еще...</a></div>');
//                	$('.listphoto').append('<div class="morephoto"><a href="#">Еще...</a></div>');
//            		offset = offset+50;
//            		if(data.length<50) {
//            			$('.morephoto').remove();
//            		}
//            	} else {
//                	$('.morephoto').remove();
//            	}
//            }
//    	});
//		return false;
//    });

//	// Action for friends
//	$('.tabs ul li a.simple-action').live("click", function(){
//    	$('.tabs ul li.simple-action').addClass('current_link');
//    	$('.tabs ul li.for-friends').removeClass('current_link');
//    	$('.tabs ul li.for-friends').html('<a href="#" class="for-friends"><span class="tl"><span class="tr">Новая акция для друзей</span></span></a>');
//    	$('#group').val(0);
//    	$('.about_friends, .grouptr').hide();
//		$(this).replaceWith('<span>' + $(this).html() + '</span>');
//		VK.callMethod('resizeWindow', 770, $('.wrapper').height());
//		return false;
//    });
//
//    $('.tabs ul li a.for-friends').live("click", function(){
//    	$('.tabs ul li.for-friends').addClass('current_link');
//    	$('.tabs ul li.simple-action').removeClass('current_link');
//    	$('.tabs ul li.simple-action').html('<a href="#" class="simple-action"><span class="tl"><span class="tr">Новая акция</span></span></a>');
//    	$('#group').val(1);
//    	$('.about_friends, .grouptr').show();
//		$(this).replaceWith('<span>' + $(this).html() + '</span>');
//		VK.callMethod('resizeWindow', 770, $('.wrapper').height());
//		return false;
//    });

    var friendsarray = [];
    <?php if($this->action['group']==1) { ?>
    $('.about_friends').show();
    $('.grouptr').show();
    friendsarray = [ <?php foreach($this->action['friends'] as $friend) echo "'".$friend."', ";?> ];
    $('.friends span').html($('.insertedfriends').size());
    <?php }?>

    $('.friends a').live('click', function(){
        $(this).parent().css("color", "#666666");
    	$(this).fb_popup({
			content_container: '.friendlist',
			//content:'',
			title: 'Выберите друзей',
			popup_id: 'popup_tpl',
			width: 530,
			height: 450,
			overflow: 'auto'
		});
        if(!friendsIsLoaded) {
            VK.api('friends.get',{fields: 'uid, first_name, last_name'},function(data) {
      		  if (data.response) { 
	        	var links = '';
	        	var checked = '';
	        	var data = data.response;
                        if(data.length > 0) {
                            jQuery.each(data, function(i, element){
                                    checked = '';
                                    for (i=0;i<friendsarray.length;i++){
                                            if (friendsarray[i]==element['uid'])  {
                                                    checked = 'checked="checked"';
                                                    break;
                                            }
                                    }
                                    links = '<table><tr><td>'+element['first_name']+' '+element['last_name']+'</td><td class="friendcheckbox">' + '<input type="checkbox" '+checked+' id="friend'+element['uid']+'" value="'+element['uid']+'"/></td></tr></table>';
                                            $('.p_pad').append(links);
                                            $('.friendlist').append(links);
                            });
                            friendsIsLoaded = true;
	        	}
      		  }
            });
        }
        VK.callMethod('resizeWindow', 770, $('.wrapper').height());
        return false;
    });
    var checkedfriends;
    $('.friendcheckbox input').live('click', function(){
        if($(this).is(':checked')) {
        	checkedfriends = '<input type="hidden" value="'+$(this).val()+'" name="friends[]" id="checkedfriend'+$(this).val()+'" class="insertedfriends"/>';
        	$(checkedfriends).appendTo('#actionform');
        	$('#friend'+$(this).val()).attr('checked', 'checked');
        	friendsarray.push($(this).val());
        } else {
            $("#checkedfriend"+$(this).val()).remove();
            $('#friend'+$(this).val()).attr('checked', false);
            for (i=0;i<friendsarray.length;i++){
            	if (friendsarray[i]==$(this).val()) friendsarray[i] = null;
            }
        }
        $('.friends span').html($('.insertedfriends').size());
        if(!isNaN(toHumanNumber($('#required_sum').val())) && $('.insertedfriends').size()>0) {
        	$('#required_sum_group').val(Math.round(100*$('#required_sum').val()/($('.insertedfriends').size()+1))/100);
        }
        if($('.insertedfriends').size()==0) {
            $('#required_sum_group').val($('#required_sum').val());
        }
    });
    //End Action for friends
    
	var hframe = $('.wrapper').height(); 
	VK.callMethod('resizeWindow', 770, hframe);
});

//$(document).ajaxStart(function(){
//		$('.morephoto').append('<span class="loading"></span>');
//	}).ajaxStop(function(){
//		$('.morephoto span').remove();
//});
</script>

<div class="header">
	<a  href="<?php echo $this->appurlorigin?>" target="_top" class="logo"></a>
	<div class="header_links">
		<div id="vk_like"></div>
		<script type="text/javascript">
		VK.Widgets.Like("vk_like", {type: "button", 
			pageUrl: '<?php echo $this->appurlorigin?>', 
			pageDescription: '<?php echo $this->appdesc?>', 
			pageTitle: '<?php echo $this->appname?>',
			text: '<?php echo $this->appdesc?>',
			verb: 1});
		</script>
	</div>
</div>

<div class="tabs">
	<ul>
		<li>
			<a href="/actions"><span class="tl"><span class="tr">Все акции</span></span></a>
		</li>
		<li>
			<a href="/actions/my"><span class="tl"><span class="tr">Мои акции</span></span></a>
			</li>
		<li>
			<a href="/actions/account"><span class="tl"><span class="tr">Мой счет</span></span></a>
		</li>
                <?php if($this->admin) {?> 
		<li>
			<a href="/actions/adminstat"><span class="tl"><span class="tr">Статистика</span></span></a>
		</li>
		<li>
			<a href="/actions/duplicates"><span class="tl"><span class="tr">Дубликаты</span></span></a>
		</li>
		<li>
			<a href="/actions/admins"><span class="tl"><span class="tr">Админы</span></span></a>
		</li>
		<?php } ?>
<!--                <span><span class="tl"><span class="tr">Новая акция</span></span></span>-->
<!--		<li class="<?php if($this->action['group']!=1) echo "current_link "; ?>simple-action">
			<?php if($this->action['group']!=1) { ?>
			<span><span class="tl"><span class="tr">Акция для всех</span></span></span>
			<?php } else {?>
			<a href="#" class="simple-action"><span class="tl"><span class="tr">Акция для всех</span></span></a>
			<?php }?>
		</li>
		<li class="<?php if($this->action['group']==1) echo "current_link "; ?>for-friends">
			<?php if($this->action['group']==1) { ?>
			<span><span class="tl"><span class="tr">Акция для друзей</span></span></span>
			<?php } else {?>
			<a href="#" class="for-friends"><span class="tl"><span class="tr">Акция для друзей</span></span></a>
			<?php }?>			
		</li>-->
	</ul>
</div>

<div class="content">
<div class="admin">
	<div class="title3">Описание акции</div>
	<div class="left">
	<form action="" method="post" enctype="multipart/form-data" id="actionform">
		<input type="hidden" value="<?php echo $this->action['id']?>" name="action_id" id="action_id" />
		<div class="new_action">
                <table id="edit_table">
			<tr><td>На что собираете:</td><td class="inp"><input name="name" maxlength="60" type="text" value="<?php echo $this->action['name']?>" id="name" /></td></tr>

			<tr><td>Подробное описание:</td><td class="inp"><textarea name="description" cols="" rows=""><?php echo $this->action['description']?></textarea></td></tr>

			<tr><td>Метки:</td><td class="inp"><input name="tags" type="text" value="<?php echo $this->action['tags']?>" /></td></tr>

			<tr class="period"><td>Дата начала:</td><td class="inp">
                    <div class="select1" id="date1">
                        <input type="text" class="datepicker" id="from" value="<?php echo date('j '.$monthNamesForInput[date('n', $this->starthiddenstamp)-1], $this->starthiddenstamp);?>" />
                        <input name="date_start" type="text" value="<?php echo $this->starthidden?>" class="settable date_start" />
                    </div>         
                    <div class="choose_end">
						<a href="#">Указать дату окончания</a>
					</div>                               
				</td></tr>
				<tr class="period choose_end_block"><td>Дата окончания:</td><td class="inp">
					<div>
						<div class="select1" id="date2">
		                    <input type="text" class="datepicker" id="to" value="<?php echo $this->endhidden==0 ? '' : date('j '.$monthNamesForInput[date('n', $this->endhiddenstamp)-1], $this->endhiddenstamp)?>" />
		                    <input name="date_end" type="text" value="<?php echo $this->endhidden==0 ? '0' : $this->endhidden?>" class="settable date_end" />
		                </div>
		                <a href="#" class="remove_end">Удалить</a>	
		                <div style="display: none;">
		                    <input type="checkbox" value="<?php if ($this->endhidden==0) { echo "1"; }?>" name="signal" id="signal" <?php if ($this->endhidden==0) {?>checked="checked" <?php }?> /> бессрочно
		                </div>
	                </div>
	            </td></tr>
                                <tr><td></td><td class="align_left"><input type="checkbox" <?php echo ($this->action['only_link']=="Y") ? 'checked="checked"' : '';?> name="only_link" id="only_link"> Сделать акцию видимой только по прямой ссылке</td></tr>
				<tr id="add_link" <?php if(strlen($this->action['url'])>4) {?>class="add_tr_closed"<?php }?>><td></td><td class="add_link"><a href="#">Добавить сайт, фотографии или видео</a></td></tr>
				<tr class="add_tr <?php if(!strlen($this->action['url'])>4) {?>add_tr_closed<?php }?>"><td class="namepad_td">Адрес сайта:</td><td class="inp pad_td"><input name="url" type="text" value="<?php echo $this->action['url']?>" /></td></tr>
				<tr class="add_tr <?php if(!strlen($this->action['url'])>4) {?>add_tr_closed<?php }?>"><td>Видео на YouTube:</td><td class="inp"><input name="video" value="<?php echo $this->action['video']?>" type="text" /></td></tr>
				<tr class="add_tr <?php if(!strlen($this->action['url'])>4) {?>add_tr_closed<?php }?>"><td>Фотографии:</td><td class="add_photo"><a href="#">добавить/удалить фотографию</a>
                                <!--служебные поля-->
                                <input type="hidden" name="urlh" id="urlh" /><input type="hidden" name="actionnameh" id="actionnameh" /><br /><br />
            <div class="photocontainer">
				<?php
				$i=0;
				//print_r($this->showphotos);
				foreach($this->showphotos as $photo) {
					?>
					<table id="img<?php echo $photo['pid']?>">
                                            <tbody><tr><td>
					<a href="#" class="del_photo"></a>
                                        <input type="hidden" name="photo[<?php echo $i?>]" value="<?php echo $photo['pid']?>" />
        			<img src="<?php echo $photo['src']?>" hspace="3" vspace="3" id="img<?php echo $photo['pid']?>" />
                                                    </td></tr></tbody>
                                        </table>
					<?php
					$i++;
				}
				?>
				</div>
				</td></tr>
                                <tr class="add_tr2 add_tr2">
                                    <td>Для кого:</td>
                                    <td class="inp">
                                        <select id="groupselect">
                                            <option value="0">Для всех</option>
                                            <option value="1" <?php if($this->action['group'] == 1) echo "selected";?>>Для друзей</option>
                                        </select>
                                    </td>
                                </tr>
                                <?php if($this->adminEdit) : ?>
                                <tr id="add_link2"><td></td><td class="add_link2"><a href="#">Изменить автора акции</a></td></tr>
                                <tr class="add_tr2 add_tr2_closed"><td>От кого публиковать:</td><td class="inp">
                                <select name="who" id="who">
                                    <option value="<?php echo $this->action['user_id']; ?>" <?php echo $this->action['page_id'] == NULL ? ' selected' : ''; ?>><?php echo $this->actionUser->name; ?></option>
                                    <?php foreach($this->adminPages as $v) : ?>
                                    <option value="<?php echo $v['page_id']; ?>" <?php echo $v['id'] == $this->action['page_id'] ? ' selected' : ''; ?>><?php echo $v['name']; ?></option>
                                    <?php endforeach; ?>
                                </select></td></tr>
                                <?php endif; ?>
			</table>
		</div>

		<div class="about_friends">
			<div class="title3">Про друзей</div>
			<div class="friends">Выбрано <span>0</span> друзей (<a href="#">выбрать</a>)</div>
		</div>

		<div class="about_money">

			<div class="title3">Про деньги</div>
			<div class="about_money_inner">
				<div>Какую сумму показывать на информере? Выберите нужный вариант:</div>
	
				<div id="cash_variants">
					<ul>
						<li<?php if($this->action['source']==0) echo ' class="curr"'; ?>><img src="/i/settings-all-32.png" alt="Всё, что есть на счете"/> 
						<div>Всё, что есть на счете</div></li>
<!--						<li<?php if($this->action['source']==1) echo ' class="curr"'; ?>><img src="/i/settings-date-32.png" alt="Только за время акции" /> 
						<div>Только за время акции</div></li>-->
						<li<?php if($this->action['source']==1) echo ' class="curr"'; ?>><img src="/i/settings-campaign-32.png" alt="Только через приложение" /> 
						<div>Только для этой акции</div></li>
					</ul>
					<input name="source" type="text" value="<?php echo $this->action['source']?>" />
				</div>
				<div class="cv_info<?php if($this->action['source']==0) echo " cv_show"; ?>">Показываем баланс вашего счёта в Яндекс.Деньгах. Также вы можете указать сумму, которая собрана другими способами.</div>
<!--				<div class="cv_info<?php if($this->action['source']==1) echo " cv_show"; ?>">Показываем все деньги, которые пришли на ваш счёт за определённый срок. Вы можете дополнительно указать сумму, которая собрана другими способами.</div>-->
				<div class="cv_info<?php if($this->action['source']==1) echo " cv_show"; ?>">Учитываем только деньги, переведенные через приложение на эту акцию. Вы также можете указать сумму, которая собрана другими способами.</div>
			</div>
			<table>
<!--				<tr class="mbegin<?php if($this->action['source']!=1) echo " tr_closed"; ?>"><td class="period">Начать отсчет с:</td><td class="inp">
					<div class="select1" id="date3">
                        <input type="text" class="datepicker" value="<?php /*echo date('j '.$monthNamesForInput[date('n', $this->ymfromdatehiddenstamp)-1], $this->ymfromdatehiddenstamp);*/?>" />
						<input name="ymfromdate" type="text" value="<?php echo $this->ymfromdatehidden;?>" class="settable ymfromdate" />
					</div>
				</td></tr>-->

				<tr><td>У вас уже есть:</td><td class="inp"><input name="current_sum" id="current_sum" type="text" value="<?php echo $this->action['current_sum']?>" />

				<p>руб. (всего – <span><?php echo ($this->balance + $this->action['current_sum'])?> руб.</span>)</p></td></tr>
				<tr class="grouptr">
					<td>Скидываемся по:</td>
					<td class="inp"><input name="required_sum_group" id="required_sum_group" type="text" value="<?php echo $this->action['required_sum_group']?>" /> <p>руб.</p></td>
				</tr>
				<tr><td>Всего нужно собрать:</td><td class="inp"><input name="required_sum" id="required_sum" value="<?php echo $this->action['required_sum'] ? $this->action['required_sum'] : ''?>" type="text" /> <p>руб.</p></td></tr>

			</table>

		</div>

		<input type="hidden" value="<?php echo $this->action['draft']?>" name="draft" id="draft" />
		<input type="hidden" value="<?php echo $this->action['group']?>" name="group" id="group" />
		<div class="new_action_buttons">
		<a href="#" class="button2"  id="publicbutton">Сохранить</a>
		<a href="#" class="button1" id="draftbutton">Сохранить черновик</a>
                <a href="#" class="button1 editcancel" id="canselbutton">Отменить</a></div>
		<?php if($this->action['group']==1) { 
		foreach($this->action['friends'] as $friend) { ?>
		<input type="hidden" value="<?php echo $friend?>" name="friends[]" id="checkedfriend<?php echo $friend?>" class="insertedfriends"/>
		<?php } }?>
	</form>

	</div>



	<div class="right">
		<div class="mini_block">
			<?php
			if($this->action['percents']>=0) {
				if($this->action['percents']==0) {
					$bkground = '0';
				} elseif($this->action['percents']<=33) {
					$bkground = '0';
				} elseif($this->action['percents']<=67) {
					$bkground = '-7';
				} else {
					$bkground = '-14';
				}
			} else {
				$bkground = '-21';
			}
			?>
			<div class="mini_block_inner">
				<div class="mb_timer"><?php echo $this->action['dates']?> <span><?php if(isset($this->action['left'])) { echo $this->action['left']; }?></span></div>
<!--                                <div class="mb_title" class="display: none;"><a href="/#app_data=<?php echo $this->action['id']?>"><?php echo mb_strlen($this->action['filteredName'], "UTF-8")<=53 ? $this->action['filteredName'] : mb_substr($this->action['filteredName'], 0, 52, "UTF-8")."…";?></a>-->
				<div class="mb_title"><a href="/#app_data=<?php echo $this->action['id']?>"><?php echo mb_strlen($this->action['filteredName'], "UTF-8")<=53 ? $this->action['filteredName'] : mb_substr($this->action['filteredName'], 0, 52, "UTF-8")."…";?></a>
				<div><a href="<?php echo $this->action['Userurl']?>" target="_blank"><?php echo mb_strlen($this->action['Username'], "UTF-8")<=18 ? $this->action['Username'] :
					mb_substr($this->action['Firstname'], 0, 1, "UTF-8").'. '.$this->action['Lastname']?></a></div></div>
				<div class="mb_money_line">
					<?php if($this->action['percents']>0) { ?>
					<div style="width:<?php echo $this->action['percents'];?>%; background-position:0 <?php echo $bkground?>px;">
						<div></div>
					</div>
					<?php } else { ?>
					<div style="width:0%; background-position:0 <?php echo $bkground?>px;">
						<div></div>
					</div>
					<?php } ?>
				</div>
				<?php if($this->action['current_sum']<1000000 && $this->action['required_sum']>999999) { ?>
					<div class="mb_collected" id="mb_collected<?php echo $this->action['id']?>">Собрано <span class="s1"><?php echo $this->action['current_sumF']; ?></span> <span>руб.</span>
					<?php if ($this->action['required_sum']>0) {?>из <span class="s2"><?php echo $this->action['required_sumF']; ?></span> <span>руб.</span><?php }?></div>
				<?php } else { ?>
					<div class="mb_collected" id="mb_collected<?php echo $this->action['id']?>">Собрано <span class="s1"><?php echo $this->action['current_sumF']; ?></span>
					<?php if ($this->action['required_sum']>0) {?>из <span class="s2"><?php echo $this->action['required_sumF']; ?></span><?php }?> <span>руб.</span></div>
				<?php }?>
			</div>
		</div>
	</div>

</div>

</div>
<?php //if($this->adminEdit) : ?>
<div style="display:none">
    <div id="<?php echo $this->user['Uid']; ?>">		
        <a href="<?php echo $this->user['Userurl']; ?>" target="_blank">
            <?php echo mb_strlen($this->action['Username'], "UTF-8") <= 18 ? $this->action['Username'] :
                    mb_substr($this->action['Firstname'], 0, 1, "UTF-8") . '. ' . $this->action['Lastname']; ?>
        </a>
    </div>
    <?php // if($this->pages != '') : ?>
        <?php if($this->adminPages) : ?>
            <?php foreach($this->adminPages as $v) : ?>
            <div id="<?php echo $v['page_id']; ?>">		
                <a href="<?php echo 'http://vk.com/club' . $v['id'] ?>" target="_blank">
                    <?php echo mb_strlen($v['name'], "UTF-8") <= 50 ? $v['name']
                            : mb_substr($v['name'], 0, 49, "UTF-8") . "…"; ?>
                </a>
            </div>
            <?php endforeach; ?>
        <?php else :?>
            <?php if(is_array($this->pages)) { 
			foreach($this->pages as $v) : ?>
            <div id="<?php echo $v['page_id']; ?>">		
                <a href="<?php echo 'http://vk.com/club' . $v['id'] ?>" target="_blank">
                    <?php echo mb_strlen($v['name'], "UTF-8") <= 50 ? $v['name']
                            : mb_substr($v['name'], 0, 49, "UTF-8") . "…"; ?>
                </a>
            </div>
            <?php endforeach;
			}	?>
        <?php endif; ?>
    <?php // endif; ?>
</div>

<div id="tmp_div" style="display:none"></div>

<div class="listphoto" style="display:none">
    <p>Фотографии должны быть в общедоступных альбомах.</p>
    <div id="file-uploader-demo1">		
        <noscript>			
            <p>Please enable JavaScript to use file uploader.</p>
                    or put a simple form for upload here 
        </noscript>         
    </div>
    <div id="photos"></div>
</div>
<div class="friendlist">
    <p>Выберите друзей для акции</p>
</div>