<link rel="stylesheet" href="<?php echo $this->baseUrl('css/ym_fb.css')?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/jquery-ui-1.8.16.custom.css')?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/jquery.fancybox-1.3.4.css')?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/reset.css')?>" type="text/css" media="screen" />

<div class="header">
	<a  href="<?php echo $this->appurl?>" target="_top" class="logo"></a>
	<div class="header_links">
		<a href="<?php echo $this->appurl?>?app_data=21354-52934" target="_top">Все акции</a> &#0149;
                <a href="<?php echo $this->appurl ?>?app_data=21354-48523" target="_top">Мои акции</a> &#0149; 
                <a href="<?php echo $this->appurl ?>?app_data=21354-98347" target="_top">Информация о счете</a>
<!--		<a href="/actions/fundraiser">Обновить балансы</a> &#0149; -->
                <?php if ($this->admin) { ?> &#0149; <span>Статистика</span> &#0149; <a href="/actions/duplicates">Дубликаты</a>
                &#0149; <a href="/actions/admins">Админы</a><?php } ?>
                <?php if($this->cancreate) { ?>
		<a href="<?php echo $this->appurl?>?app_data=21354-23895" class="button1" target="_top"><img src="/i/b_plus.gif" alt="" />Создать акцию</a>
		<?php } ?>
	</div>
</div>
<div class="content">
<?php if($this->error) {?>
<div id="action_is_closed"><a href="#">закрыть</a> <?php echo $this->error?></div>
<?php } ?>
	<div class="left">		
		<div>
			<div class="title2">Статистика акций</div>
			<table class="stat_table">
			<tr>
				<td>Всего акций</td>
				<td  class="st_pay"><?php echo $this->countAll?></td>
			</tr>
			<tr>
				<td>Акций в ТОП (отмеченные, незаблокированные)</td>
				<td class="st_pay"><?php echo $this->countTop?></td>
			</tr>
			<tr>
				<td>Черновики</td>
				<td class="st_pay"><?php echo $this->countDraft?></td>
			</tr>
			<tr>
				<td>Новые</td>
				<td class="st_pay"><?php echo $this->countNew?></td>
			</tr>
			<tr>
				<td>Скрытые</td>
				<td class="st_pay"><?php echo $this->countHidden?></td>
			</tr>
			<tr>
				<td>Заблокированные</td>
				<td class="st_pay"><?php echo $this->countBlocked?></td>
			</tr>
			<tr>
				<th colspan="2">Акций создано</th>
			</tr>
			<tr>
				<td>За сегодня</td>
				<td class="st_pay"><?php echo $this->countThisDay?></td>
			</tr>
			<tr>
				<td>За вчерашний день</td>
				<td class="st_pay"><?php echo $this->countLastDay?></td>
			</tr>
			<tr>
				<td>За эту неделю</td>
				<td class="st_pay"><?php echo $this->countThisWeek?></td>
			</tr>
			<tr>
				<td>За прошлую неделю</td>
				<td class="st_pay"><?php echo $this->countLastWeek?></td>
			</tr>
			<tr>
				<td>2 недели назад</td>
				<td class="st_pay"><?php echo $this->count2Week?></td>
			</tr>
			<tr>
				<td>3 недели назад</td>
				<td class="st_pay"><?php echo $this->count3Week?></td>
			</tr>
			<tr>
				<td>За этот месяц</td>
				<td class="st_pay"><?php echo $this->countThisMonth?></td>
			</tr>
			<tr>
				<td>За прошлый месяц</td>
				<td class="st_pay"><?php echo $this->countLastMonth?></td>
			</tr>
			<tr>
				<td>2 месяца назад</td>
				<td class="st_pay"><?php echo $this->count2Month?></td>
			</tr>
			<tr>
				<th colspan="2">Платежи по акциям</th>
			</tr>
			<tr>
				<td>За сегодня</td>
				<td class="st_pay"><?php echo $this->paymentsThisDay?></td>
			</tr>
			<tr>
				<td>За вчерашний день</td>
				<td class="st_pay"><?php echo $this->paymentsLastDay?></td>
			</tr>
			<tr>
				<td>На этой неделе</td>
				<td class="st_pay"><?php echo $this->paymentsThisWeek?></td>
			</tr>
			<tr>
				<td>На прошлой неделе</td>
				<td class="st_pay"><?php echo $this->paymentsLastWeek?></td>
			</tr>
			<tr>
				<td>2 недели назад</td>
				<td class="st_pay"><?php echo $this->payments2Week?></td>
			</tr>
			<tr>
				<td>3 недели назад</td>
				<td class="st_pay"><?php echo $this->payments3Week?></td>
			</tr>
			<tr>
				<td>В этом месяце</td>
				<td class="st_pay"><?php echo $this->paymentsThisMonth?></td>
			</tr>
			<tr>
				<td>В прошлом месяце</td>
				<td class="st_pay"><?php echo $this->paymentsLastMonth?></td>
			</tr>
			<tr>
				<td>2 месяца назад</td>
				<td class="st_pay"><?php echo $this->payments2Month?></td>
			</tr>
			<?php /* foreach($this->operations as $operation) {?>
				<tr>
					<td class="st_date"><?php echo date("d M", $operation->getDateTime())?></td>
					<td  class="st_pay"><?php 
					echo (ceil($operation->getAmount())>$operation->getAmount()) 
					? number_format($operation->getAmount(), 2, ',', ' ')
					: number_format($operation->getAmount(), 0, ',', ' ') ?> руб.</td>
					<td><?php echo $operation->getTitle()?></td>
				</tr>
			<?php } */?>
			</table>
		</div>
	</div>

	<div class="right">
		
	</div>
</div>
