<link rel="stylesheet" href="<?php echo $this->baseUrl('css/ym_fb.css')?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/jquery-ui-1.8.16.custom.css')?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/jquery.fancybox-1.3.4.css')?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/reset.css')?>" type="text/css" media="screen" />
<style>

.left table tr {
	border:1px solid #ddd;
	padding:3px;
}
.left table td {
	padding:3px;
	font-size:11px
}
</style>
<div class="header">
	<a  href="<?php echo $this->appurl?>" target="_top" class="logo"></a>
	<div class="header_links">
		<a href="<?php echo $this->appurl?>?app_data=21354-52934" target="_top">Все акции</a> &#0149;
                <a href="<?php echo $this->appurl ?>?app_data=21354-48523" target="_top">Мои акции</a> &#0149; 
                <a href="<?php echo $this->appurl ?>?app_data=21354-98347" target="_top">Информация о счете</a>
                <?php if ($this->admin) { ?> &#0149; <a href="/actions/adminstat">Статистика</a> &#0149; <span>Дубликаты</span>
                &#0149; <a href="/actions/admins">Админы</a><?php } ?>
                <?php if ($this->cancreate) { ?>
                <a href="<?php echo $this->appurl ?>?app_data=21354-23895" class="button1" target="_top"><img src="/i/b_plus.gif" alt="" />Создать акцию</a>
                <?php } ?>
	</div>
</div>
<div class="content">
<?php if($this->error) {?>
<div id="action_is_closed"><a href="#">закрыть</a> <?php echo $this->error?></div>
<?php } ?>
	<div class="left">		
		<div>
			<div class="title2">Дубликаты акци<?php if(isset($this->id)) echo "и ".$this->id; else echo "й";?></div>
			<table width="100%">
			<?php foreach($this->actions as $action) {?>
			<tr>
				<td><a href="<?php echo $this->appurl?>?app_data=<?php echo $action['id']?>" target="_blank"><?php echo $action['name'];?></a></td>
				<td><a href="<?php echo $this->appurl?>?app_data=<?php echo $action['dupl']?>" target="_blank">Дубликат акции <?php echo $action['dupl'];?></a></td>
				<td><a href="/actions/duplicates?check=<?php echo $action['id']; ?><?php if(isset($this->id)) echo "&id=".$this->id;?>">Снять подозрения</a></td>
			</tr>
			<?php } ?>
			</table>
		</div>
	</div>

</div>
