<link rel="stylesheet" href="<?php echo $this->baseUrl('css/font.css') ?>" id="font-css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/styles.css') ?>" />
<link  rel="stylesheet" href="<?php echo $this->baseUrl('css/jquery-ui.css') ?>">
<link  rel="stylesheet" href="<?php echo $this->baseUrl('css/jquery.tagit.css') ?>">
<link  rel="stylesheet" href="<?php echo $this->baseUrl('css/tagit.ui-zendesk.css') ?>" >

<div class="header">
    <a class="logo" href="<?php echo $this->appurl?>" target="_top"><img src="/img/logo.png"></a>
    <?php if($this->cancreate) { ?>
    	<a class="btn pull-right" href="<?php echo $this->appurl?>?app_data=21354-23895" target="_top">Создать акцию</a>
    <?php } ?>
    <div class="nick"><p><?php echo $this->user_name;?></p></div>
    <div class="clear"></div>
</div>
<?php //var_dump($this->photos)?>
<div class="content">
	<div class="actions">
		<div class="panel">
	        <div class="filter">
	          <a href="#" class="active">Все акции</a>
	          <a href="<?php echo $this->appurl ?>" target="_top">Популярные</a>
	          <a href="<?php echo $this->appurl ?>?app_data=21354-48523" target="_top">Мои акции</a>
	          <a href="<?php echo $this->appurl ?>?app_data=21354-98347" target="_top">Информация о счете</a>
			<?php if ($this->admin) { ?> 
			<a href="/actions/adminstat" class="adminlink">Статистика</a>
			<a href="/actions/duplicates" class="adminlink">Дубликаты</a>
            <a href="/actions/admins" class="adminlink">Админы</a> 
            <a href="/rubric/admin" class="adminlink">Рубрики</a>
			<?php } ?>
	        </div>
	        <div class="search">
	          <form action="/actions/index" method="get">
	            <div class="control">
	              <ul id="myTags"></ul>
	              <div class="submit">
	                <button type="submit"></button>
	              </div>
	            </div>
	          </form>
	        </div>
		</div>
		<div class="action_items">
			<div class="gradient"></div>
			<div class="section">
				<?php 
				$i = 0;
				for($ic=0;$ic<3;$ic++){ ?>
				<div class="col" id="col<?php echo $ic;?>" >
					<?php 
					for($k=0;$k<3;$k++) { 
						if(!isset($this->actions[$i]) || empty($this->actions[$i])) continue;
						$action = $this->actions[$i];
					?>
					<div class="item">
					<?php if(!empty($this->photos[$action['id']])) {?>
		              <div class="pic">
		                <img src="<?php echo $this->photos[$action['id']]?>">
		              </div>
		            <?php } ?>
		              <div class="desc">
		                <p><a href="<?php echo $this->appurl ?>?app_data=<?php echo $action['id'] ?>" target="_top">
		                <?php echo $action['filteredName']; ?>
		                </a></p>
		                <a href="<?php echo $action['Userurl'] ?>" class="name" target="_blank"><?php  echo $action['Username']; ?></a>
		              </div>
		              <div class="bot">
		                <div class="b1"><p>Собрано <?php echo $action['current_sumF'] . $action['current_sum_suffix']; ?> руб.</p></div>
		                <div class="b2">
		                  <div class="send">
		                  	<form action="<?php echo $this->paymenturl;?>" enctype="application/x-www-form-urlencoded" target="_blank" method="get">
				                <div class="control"><input type="text" name="sum" value="<?php echo $action['paymentsum'];?>"> руб.</div>
				                <input type="submit" class="submit" value="Передать">
				                <input type="hidden" name="receiver" value="<?php echo $action['receiver']?>"/>
				                <input type="hidden" name="Formcomment" value="<?php echo ('На акцию в Facebook «'.$action['name'].'»')?>"/>
				                <input type="hidden" name="destination" value="<?php echo ('Для акции «'.$action['name'].'» от пользователя facebook.com/' . $this->user_id . '. Чтобы отправить деньги анонимно, удалите весь комментарий.')?>"/>
				                <input type="hidden" name="_openstat" value="socapp;fb;p2p;list"/>
				                <input type="hidden" name="label" value="fb_<?php echo $action['id']?>"/>
				            </form>
		                  </div>
		                  <div class="q">
		                    <i></i>
		                    <div class="tooltip">
		                      <div class="top"></div>
		                      <div class="section">
		                        <p>Вы можете передать нужную сумму с помощью Яндекс.Денег, или воспользоваться <a href="<?php echo $this->appurl ?>?app_data=21354-34621" target="_top">другими способами</a>.</p>
		                      </div>
		                      <div class="bot"></div>
		                    </div>
		                  </div>
		                </div>
		              </div>
		            </div>
				<?php $i++; }  ?>
				</div>
				<?php } ?>
				<div class="clear"></div>
			</div>
		</div>
		<?php if(count($this->actions)>9){?><div class="show_more"><a href="#" class="btn" id="show_more">Показать ещё</a></div><?php }?>
	</div>
</div>


<?php /*?><script type='text/javascript' src='<?php echo $this->baseUrl('js/index.js') ?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/shelp.js') ?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/jquery.autoSuggest.minified.js') ?>'></script>
<link type='text/css' href='<?php echo $this->baseUrl('css/autoSuggest.css') ?>' rel='stylesheet' media='screen' />

<script>    
    function getSum(arr) {
        for(var i=0; i<arr.length; i++) {
            (function(i) {
                $.ajax({
                    url: fundAjaxUrl, 
                    type: "GET",
                    data: {
                        action_id: arr[i].id
                    },
                    success: function (data) {
                        sum = parseInt(arr[i].all_sum) + parseInt(arr[i].current_sum) + (data.sum) ? parseInt(data.sum) : parseInt(data.balance);
                        console.log(parseInt(arr[i].required_sum));
                        if(parseInt(arr[i].required_sum) == 0 && sum == 0) {
//                            setrightworeq(arr[i].id, parseInt(arr[i].required_sum), sum);
//                        } else if (parseInt(arr[i].required_sum) > 0 && sum == 0) {
//                            setrightWithReqWoBalC(arr[i].id, parseInt(arr[i].required_sum), sum);
                        } else if (parseInt(arr[i].required_sum) > 0 && sum > 0) {
                            setrightWithReqWoBalC(arr[i].id, parseInt(arr[i].required_sum), sum);
                        } else if (parseInt(arr[i].required_sum) == 0 && sum > 0) {
                            setrightWoReqWBalC(arr[i].id, parseInt(arr[i].required_sum), sum);
                        }
                    }
                });
            })(i);
        }
    }
    var actions = <?php echo json_encode($this->actions); ?>;
    getSum(actions);
    var appurl = '<?php echo $this->appurl;?>';
    var apphost = '<?php echo $this->host;?>';
    $(document).ready(function(){
//        $("div.mini_block_outer div.mb_collected").each(function() {
//        });
        <?php if ($this->selected) { ?>
        $('#<?php echo $this->selected ?>').replaceWith('<span>' + $('#<?php echo $this->selected ?>').html() + '</span>');
        <?php } ?>
        $('.mb_help').hide();
        $('.mini_block_inner').live('mouseover', function(){
            $(this).find('.mb_collected').hide();
            $(this).find('.mb_help').show();
            $(this).find('.mb_shelp').show();
		
        });
        $('.mini_block_inner').live('mouseout', function(){
            $(this).find('.mb_help').hide();
            $(this).find('.mb_shelp').hide();
            $(this).find('.mb_collected').show();		
        });

        var search = false;
        if($('.search input').val()!="Поиск акций") {
            search = $('.search input').val();
        }

        var page = 1;
	
        $('.uiButton').live('click', function(){
            var next = $(this).hasClass('next');
            //alert(next);
            $.ajax({
                url: pageAjaxUrl, 
                type: "GET",
                dataType: "json",
                data: {
                    page: page,
                    search: search,
                    selected: '<?php echo $this->selected ?>',
                    next: next
                },
                success: function (data) { 
                    if(data.next == true) {
                        if($('#rfloat a').last().hasClass('uiButtonDisabled')) {
                            $('#rfloat a').last().removeClass('uiButtonDisabled');
                        }	
                    } else {
                        if(!$('#rfloat a').last().hasClass('uiButtonDisabled')) {
                            $('#rfloat a').last().addClass('uiButtonDisabled');
                        }	
                    }
                    if(data.prev == true) {
                        if($('#rfloat a').first().hasClass('uiButtonDisabled')) {
                            $('#rfloat a').first().removeClass('uiButtonDisabled');
                        }
                    } else {
                        if(!$('#rfloat a').first().hasClass('uiButtonDisabled')) {
                            $('#rfloat a').first().addClass('uiButtonDisabled');
                        }	
                    }
                            
                    if(data.li.length>0) {
                        var tr='';
                        if(next) {
                            page = page + 1;
                        } else {
                            page = page - 1;
                        }
            		
                        $('ul.all_actions_list li').html('');                	
                        for(key in data.li) {
                            tr = data.li[key];
                            $('ul.all_actions_list li').append(tr);
                        }
                        FB.Canvas.setAutoGrow();
                        $('.mb_help').hide();
                    }
                    actions = data.actions;
                    getSum(data.actions);
                }
            });
            return false;
        });
    });
</script>
<div class="header">
    <a  href="<?php echo $this->appurl ?>" target="_top" class="logo"></a>
    <div class="header_links">
        <span>Все акции</span> &#0149; <a href="<?php echo $this->appurl ?>?app_data=21354-48523" target="_top">Мои акции</a> &#0149; 
        <a href="<?php echo $this->appurl ?>?app_data=21354-98347" target="_top">Информация о счете</a>
        <?php if ($this->admin) { ?> &#0149; <a href="/actions/adminstat">Статистика</a> &#0149; <a href="/actions/duplicates">Дубликаты</a>
            &#0149; <a href="/actions/admins">Админы</a> &#0149; <a href="/rubric/admin">Р</a><?php } ?>
        <?php if ($this->cancreate) { ?>
            <a href="<?php echo $this->appurl ?>?app_data=21354-23895" class="button1" target="_top"><img src="/i/b_plus.gif" alt="" />Создать акцию</a>
        <?php } ?>
    </div>
</div>

<div class="top_line">
    <form method="post" enctype="application/x-www-form-urlencoded" class="search">
        <input name="search" type="text" 
               value="<?php echo ($this->search) ? $this->search : "Поиск акций" ?>" 
               onfocus="this.value=='Поиск акций'?this.value='':void(0)" 
               onblur="this.value==''?this.value='Поиск акций':void(0)" />
        <button type="submit">&nbsp;</button>
    </form>

    <div class="tl_links"><a href="/actions" id="all">Все</a> <a href="/actions/?pop=y" id="pop">Популярные</a>

        <?php if ($this->admin) { ?> 
            <a href="/actions/?top=y" id="top">Выделенные</a> 
            <a href="/actions/?completed=y" id="completed">Завершенные</a> 
            <a href="/actions/?hidden=y" id="hidden">Скрытые</a> 
            <a href="/actions/?blocked=y" id="blocked">Заблокированные</a>
        <?php } ?>
    </div>
</div>
<div class="content">
    <?php if ($this->error) { ?>
        <div id="action_is_closed"><a href="#">закрыть</a> Сбор денег по этой акции уже закончен, но вы можете поддержать другое доброе дело.</div>
    <?php } ?>
    <?php if ($this->search) { ?>
        <div>
            <em>Найдено акций: <?php echo count($this->actions) ?></em>
        </div>
    <?php } ?>

    <div class="slider"  id="main_slider">
        <ul class="all_actions_list">
            <li>
                <?php
                if (isset($this->actions)) {
                    $i = 1;
                    ?>
                    <?php
                    foreach ($this->actions as $action) {
                        if (!isset($action['percents']))
                            $action['percents'] = 0;
                        if (!isset($action['required_sumF']))
                            $action['required_sumF'] = '';
                        if (!isset($action['current_sumF']))
                            $action['current_sumF'] = '';
                        if ($action['percents'] >= 0 && $action['completed'] == 'N') {
                            if ($action['percents'] == 0) {
                                $bkground = '0';
                            } elseif ($action['percents'] <= 33) {
                                $bkground = '0';
                            } elseif ($action['percents'] <= 67) {
                                $bkground = '-7';
                            } else {
                                $bkground = '-14';
                            }
                        } else {
                            $bkground = '-21';
                        }
                        if ($i > 9)
                            break;
                        ?>			
                        <div class="mini_block_outer<?php if (($i % 3) == 0) echo " last"; ?>">
                            <div class="mini_block">
                                <div class="mini_block_inner">
                                    <div class="mb_timer"><?php echo $action['dates'] ?> <span><?php
                if (isset($action['left'])) {
                    echo $action['left'];
                }
                        ?></span></div>
                                    <?php if ($this->admin && $action['top'] == 'Y') { ?><img src="/i/symbol-favi-24.png" alt="Акция в ТОПе"  class="mb_ico" /><?php } ?>
        <?php if ($this->admin && $action['blocked'] == 'Y') { ?><img src="/i/symbol-rejected-24.png" alt="Акция заблокирована администратором"  class="mb_ico" /><?php } ?>
                                        <?php if ($this->admin && $action['dupl'] > 0 && $action['checked'] == 0) { ?><a href="/actions/duplicates?id=<?php echo $action['dupl'] ?>"><img src="/i/copy_file.png" alt="Подозрение на дубликат"  class="mb_ico" /></a><?php } ?>
                                    <div class="mb_title">
                                        <a href="<?php echo $this->appurl ?>?app_data=<?php echo $action['id'] ?>" target="_top"><?php echo mb_strlen($action['filteredName'], "UTF-8") <= 50 ? $action['filteredName'] : mb_substr($action['filteredName'], 0, 49, "UTF-8") . "…"; ?></a> 
                                                <?php if ($action['page_id'] != NULL) : ?>
                                            <div><a href="<?php echo $action['Pagelink'] ?>" target="_blank"><?php
                                        echo mb_strlen($action['Pagename'], "UTF-8") <= 40 ? $action['Pagename'] :
                                                mb_substr($action['Pagename'], 0, 39, "UTF-8") . '...';
                                                    ?></a></div>
                                                <?php else : ?>
                                            <div><a href="<?php echo $action['Userurl'] ?>" target="_blank"><?php
                                echo mb_strlen($action['Username'], "UTF-8") <= 18 ? $action['Username'] :
                                        mb_substr($action['Firstname'], 0, 1, "UTF-8") . '. ' . $action['Lastname']
                                                    ?></a></div>
        <?php endif; ?>
                                    </div>
                                    <div class="mb_money_line">
                                        <?php if ($action['percents'] > 0) { ?>
                                            <div style="width:<?php echo $action['percents']; ?>%; background-position:0 <?php echo $bkground ?>px;">
                                                <div></div>
                                            </div>
                                        <?php } else { ?>
                                            <div style="width:0%; background-position:0 <?php echo $bkground ?>px;">
                                                <div></div>
                                            </div>
        <?php } ?>
                                    </div>
                                    <div class="mb_collected" id="mb_collected<?php echo $action['id'] ?>">Собрано <span><?php echo $action['current_sumF'] . (isset($action['current_sum_suffix']) ? $action['current_sum_suffix'] : ''); ?></span> 
        <?php if ($action['required_sum'] > 0) { ?>из <span><?php echo $action['required_sumF']; ?></span><?php } ?> <span>руб.</span></div>

                                        <a id="mb_help<?php echo $action['id'] ?>" href="https://money.yandex.ru/direct-payment.xml?receiver=<?php echo $action['receiver'] ?>&Formcomment=<?php echo urlencode('На акцию в Facebook «' . $action['name'] . '»') ?>&destination=<?php echo urlencode('Для акции «'.$action['name'].'» от пользователя facebook.com/' . $this->user_id . '. Чтобы отправить деньги анонимно, удалите весь комментарий.') ?>&_openstat=socapp;fb;p2p;wid&label=fb_<?php echo $action['id'];?>" target="_blank" class="mb_help">Помочь деньгами</a>
                                        <a data-id="<?php echo $action['id']?>" style="display:none;" href="#" title="Рассказать" class="mb_shelp"></a>
                                </div>
                            </div>
                        </div>
                        <?php
                        $i++;
                    }
                    ?>
    <?php } ?>
            </li>
        </ul>
    </div>
<?php if (count($this->actions) > 9) { ?>
        <div id="rfloat">
            <a data-href="/?page=-1" role="button" class="prev uiButtonDisabled uiButton uiButtonNoText"><i class="mrs customimg img sp_4v59vo sx_a84f00"></i><span class="uiButtonText"></span></a>
            <a data-href="/?page=1" role="button" 
               class="next <?php if (count($this->actions) <= 1) echo "uiButtonDisabled"; ?> uiButton uiButtonNoText"><i class="mrs customimg img sp_4v59vo sx_224a55"></i><span class="uiButtonText"></span></a>
        </div>
<?php } ?>
</div>
<div id="shelp"></div>
<? */?>