<?php 
header('P3P: CP="IDC DSP COR CURa ADMa OUR IND PHY ONL COM STA"');
?>
<!doctype html>
<html xmlns:og="http://ogp.me/ns#"
      xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
<?php 
	$translate = Zend_Registry::get('TranslationObject');
	$config = Zend_Registry::get('appConfig');
	$locale = $translate->getLocale();
	echo $this->headMeta();
	if(strlen($this->headTitle())>1) echo $this->headTitle(); else echo "<title>".$config->ymoney->APP_NAME."</title>";
?>
<!--[if lte IE 9]>
  <script src="<?php echo $this->baseUrl('js/libs/PIE.js')?>"></script>
  <script src="<?php echo $this->baseUrl('js/libs/jquery.placeholder.min.js')?>"></script>
<![endif]-->
<!--[if lt IE 9]>
  <script src="<?php echo $this->baseUrl('js/libs/html5shiv.js')?>"></script>
<![endif]-->
<script type='text/javascript' src='<?php echo $this->baseUrl('js/libs/jquery-1.8.0.min.js')?>'></script>
<script type='text/javascript' src="<?php echo $this->baseUrl('js/libs/jquery.mousewheel.js')?>"></script>
<?php /* ?><link rel="stylesheet" href="<?php echo $this->baseUrl('css/ym_fb.css')?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/jquery-ui-1.8.16.custom.css')?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/jquery.fancybox-1.3.4.css')?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/reset.css')?>" type="text/css" media="screen" /><?*/?>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/jquery.validate.min.js')?>'></script>
<script src="https://connect.facebook.net/ru_RU/all.js?xfbml=1&appId=<?php echo $config->ymoney->APP_ID?>" type="text/javascript"></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/jquery.ui.datepicker-ru.js')?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/popup.js')?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/jquery.fancybox-1.3.4.js')?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/shelp.js') ?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/libs/jquery-ui.min.js') ?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/libs/tag-it.min.js') ?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/jquery.autoSuggest.minified.js') ?>'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl('js/scripts.js')?>'></script>
<script type='text/javascript' src="<?php echo $this->baseUrl('js/app.js')?>"></script>
<?php echo $this->headScript(); ?>
</head>
<!--[if IE 8 ]>
<body class="ie ie8">  <![endif]-->
<!--[if IE 9 ]>
<body class="ie ie9">  <![endif]-->
<!--[if !(IE)]><!-->
<body><!--<![endif]-->
<div id="fb-root"></div>
<script>
  FB.init({
    appId      : '<?php echo $config->ymoney->APP_ID?>',
    status     : true, // check login status
    cookie     : true, // enable cookies to allow the server to access the session
    oauth      : true, // enable OAuth 2.0
    xfbml      : true  // parse XFBML
  });
window.fbAsyncInit = function() {
	FB.Canvas.setAutoGrow();
};
</script>

<div class="wrapper">
	<?php echo $this->layout()->content; ?>
</div>
</body>
</html>