<?php

namespace Vmeste\SaasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonorRepository extends EntityRepository
{
}
