<?php

namespace Vmeste\SaasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IpRepository extends EntityRepository
{

    public function incrementAttempt($clientIp)
    {
        $query = $this->_em
            ->createQuery('UPDATE Vmeste\SaasBundle\Entity\Ip i SET i.attempt = i.attempt + 1 WHERE i.ip = :ip')
            ->setParameter('ip', $clientIp);
        $result = $query->getResult();
        return $result;
    }

}
