<?php

namespace Vmeste\SaasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SysEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SysEventRepository extends EntityRepository
{
}
