<?php

namespace Vmeste\SaasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * YandexKassaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YandexKassaRepository extends EntityRepository
{
}
